argotorg/sourcify

.circleci/config.yml
.gitignore
package.json

I've update config to work on both node version 10 and 12.

Circleci working on node versions 10 and 12

---

.dockerignore
.gitignore
Dockerfile.healthcheck
Dockerfile.monitor
Dockerfile.server
README.md
docker-compose.yaml
health_check.sh
server.js

This is a first version of health endpoint and docker-compose and dockerfile. It's not optimized version but it's quick and dirty first implementation. Please test it and let me know if there are any problems. 
Health endpoint has been added, will soon also add a service that pings it every 60 seconds.

Adding health endpoint

---

package.json

**PR targets #46**
Should get CI to run green. The unit tests are outside the compose and just need an extra env variable set...

Set LOCALCHAIN_URL for unit tests

---

.circleci/config.yml
.env
.gitmodules
build_and_publish_docker_images.sh
docker-compose-build.yaml
docker-compose-prod.yaml
docker-compose-testing.yaml
docker-compose.yaml
ui/.env

Building and publishing docker images to docker hub with tags depending on the branch.
Stable tag is built from master branch and latest from staging (as we don't have develop). 
Also tag is build for every branch other than master, staging and develop and pushed to the docker hub, so PR's can also be tested with docker images locally just by changing the tag. This is optional and can be removed.
Next step is to add CD part of the pipeline (optional) similar to the script here: https://github.com/blockchain-it-hr/zokrates-remix-plugin/blob/master/scripts/deploy.sh
-> user ssh to server, then fetches latest docker-compose.yaml from the branch, or clones a repo for that branch and then pulls latest changes with docker-compose pull and updates containers with docker-compose up.

Feature ci docker

---

.circleci/config.yml
deploy.sh
injector.js
validator.js

CD part is ready.
https://circleci.com/gh/ethereum/source-verify/264

Feature cd

---

injector.js
validator.js

Current naive implementation of the validator. Implementation still needs to be discussed.
DO NOT MERGE!

[WIP] Feature validator

---

src/server.ts

**PR targets #59**
Fixes #60 
Switched to throwing JS errors instead of strings during the refactor but they weren't rendering correctly in the UI. 
With changes....

Send server error message correctly

---

.env.latest
scripts/localchain.js
ui/App.js

**PR targets 59**
Fixes a few bugs found by @edisinovcic while manually testing the deployments. Changes are:
+ only show localhost:8545 in UI when using env.latest or env.testing
+ always deploy localchain contracts to same address
+ require mainnet contracts to submit with an address
The localchain contracts are now always deployed to:
```
localchain    | ==========================================
localchain    | Deployed Contracts  |  Addresses          
localchain    | ==========================================
localchain    | 
localchain    | Simple.sol:           0x8168f192F7432C93FCb16e039B57FB890AaB3230
localchain    | SimpleWithImport.sol: 0x0Ef7de872C7110d6020fa5e62d7cD31Fd90FF811
```

Fix UI bugs for staging

---

scripts/build_and_publish_docker_images.sh

**PR targets 59**
Uses env.latest when publishing to the staging branch, env.build when publishing master.

Use branch specific env files when publishing

---

package-lock.json
package.json

Fixes crash seen in CI at [circle 444](https://circleci.com/gh/ethereum/source-verify/444)
This dep is only used by the unit tests.

Upgrade ipfs-unixfs to ^1.0.0

---

package-lock.json
package.json
src/injector.ts
src/server.ts
src/utils.ts
test/injector.js
test/server.js
test/sources/pass/simple.literal.js
test/utils.js

**PR targets #84**
+ Fixes the bug discovered in #6, where submitting a single file always errored with 'Metadata not found'
+ Adds validation checks for `address` and `chain` parameters in injector
+ Adds status codes to server error responses
+ Adds unit tests for `server.ts`

Validate server inputs / add server unit tests

---

src/server.ts
src/utils.ts

This is a simple check that tries to find files in local repository by network name and address.
Do we need more detailed check here?

Adding address check

---

scripts/setup.sh
src/injector.ts
src/server.ts

Attempting to resolve #132....

Pass server logger to injector

---

src/server.ts

Disable silent option for server

---

package-lock.json
package.json
src/server.ts
src/utils.ts

This serves as "raw repository". It returns either URLs to files in folder and subfolders or actual files. 
Files are not send via sendFile because there are more then one and express doesn't support sending multiple files in single response, maybe having some better of doing this would be good?

Adding file retrieving on server

---

environments/https-portal.yaml
environments/monitor.yaml
environments/server.yaml
environments/ui.yaml
scripts/prepare.sh

Adding https portal so automatic generation and renewal of certificates are added in docker without need to manage this externally. 
Example is: https://contractrepo.verification.shardlabs.io/

Adding https portal

---

.gitignore
scripts/chain_name_to_id_mapper.sh
src/s3sync/login_sync_s3.sh

Script that migrates repository data from old contract name mapping (by name) to new naming by chain it.

script for mapping chainName to chainId

---

.circleci/config.yml

Add nightly workflow in CI for Monitor E2E

---

ui/.env.development
ui/package-lock.json
ui/package.json
ui/src/common/constants.ts
ui/src/components/icons/index.tsx
ui/src/components/layout/Header.tsx
ui/src/components/verifier/Verifier.tsx
ui/src/styles/components/_header.scss
ui/webpack.common.js

Solves: https://github.com/ethereum/sourcify/issues/218

Ui rewrite

---

src/utils.ts

Resolves: https://github.com/ethereum/sourcify/issues/219

Changing timestamp type from string to number

---

src/server.ts

Resolves: https://github.com/ethereum/sourcify/issues/231

checkByAddresses returns chainId property

---

Sourcify.postman_collection.json
src/injector.ts
src/monitor.ts
src/server.ts
src/sourcify.ts
src/utils.ts
test/injector.js
test/monitor.js
test/server.js
test/sourcify.js
ui/package-lock.json
ui/package.json
ui/src/api/verifier.ts
ui/src/components/Spinner.tsx
ui/src/components/verifier/Verifier.tsx
ui/src/reducers/verifierReducer.ts
ui/src/styles/components/_form.scss
ui/src/styles/components/_loading-overlay.scss
ui/src/styles/components/_notification.scss
ui/src/types.ts
ui/src/utils/index.ts

Check by address returns chainId property.
Adding quick address check on UI without having to click on verify button.
Original metadata name perserved.

Minor upgrades, bug fixes

---

.circleci/config.yml
Sourcify.postman_collection.json
scripts/monitor_ci.sh
src/server/controllers/FileController.ts
src/server/routes.ts
src/server/services/FileService.ts

getTreeByChainAndAddress and getByChainAndAddress endpoints did not work.
Also, express-validator now checks params from request properly.

fileController API fix

---

services/verification/package-lock.json
services/verification/package.json
services/verification/src/services/Injector.ts
services/verification/src/services/VerificationService.ts
services/verification/src/utils.ts
src/config.ts
src/monitor/monitor.ts
src/server/server.ts

When creating Injector instance, provided endpoints are tested if they are reachable. 
If they are not, everything is logged as a warning.

verificationService checkEndpoint method

---

.circleci/config.yml
.dockerignore
Dockerfile
environments/.dockerignore
src/Dockerfile.localchain
src/Dockerfile.server

Server dockerfile is built using lerna bootstrap and latest services sources from the repository.
Monitor docker is blocked for now in the CI to use the old version so we can test services on our staging environment without waiting for the monitor fix.

Services docker support

---

.vscode/launch.json
package-lock.json
package.json
scripts/publish_to_npm.sh
services/core/package-lock.json
services/core/package.json
services/core/src/utils/types.ts
services/validation/README.md
services/validation/package-lock.json
services/validation/package.json
services/validation/src/CheckedContract.ts
services/validation/src/ValidationService.ts
services/verification/README.md
services/verification/package-lock.json
services/verification/package.json
services/verification/src/services/Injector.ts
services/verification/src/services/VerificationService.ts
services/verification/src/utils.ts
src/common/validators/validators.ts
src/monitor/monitor.ts
src/server/controllers/FileController.ts
src/server/controllers/VerificationController.ts
src/server/middlewares/GenericErrorHandler.ts
src/server/middlewares/NotFoundError.ts
src/server/routes.ts
src/server/server.ts

Added simple examples on how to use verification service as a module.
Small fixes with repository path handling.
Packages renamed to @ethereum-sourcify/core, @ethereum-sourcify/validation and @ethereum-sourcify/verification

verification readme

---

environments/monitor.yaml
scripts/setup.sh

Monitor container is restricted to use maximum 2GB of memory and 2 CPU cores.

monitor container resources restricted

---

services/core/src/services/FileService.ts

closes https://github.com/ethereum/sourcify/issues/295

findByAddress case insensitive

---

src/monitor/monitor.ts

Two Monitor issues are fixed:
- object being passed to Injector did not have its data assembled in the required properties
- contracts may specify both ipfs and swarm as their source point; this led to multiple deletions in the sourceQueue

Fix monitor

---

.circleci/config.yml
environments/monitor.yaml
package.json
scripts/monitor_ci.js
src/Dockerfile.monitor
src/monitor/monitor.ts

Monitor has been fixed and now also fetches contracts from xDai chain.
It is using local solc binaries if they are available to save time on each recompilation.
Dockerfile is modified to use lerna.

Monitor enable

---

README.md
Sourcify.postman_collection.json
docs/api/server/verification1/verify.md
docs/api/server/verification2/exchange-object.md
docs/api/server/verification2/verify-validated.md
environments/https-portal.yaml
scripts/setup.sh
services/core/src/chains.json
services/core/src/utils/CheckedContract.ts
services/core/src/utils/types.ts
services/core/src/utils/utils.ts
services/verification/src/services/Injector.ts
services/verification/src/utils.ts
src/monitor/monitor.ts
src/server/controllers/VerificationController-util.ts
src/server/controllers/VerificationController.ts
test/server.js
test/testcontracts/1_Storage/1_Storage.sol
test/testcontracts/1_Storage/metadata.json
ui/src/common/constants.ts

- Matic support
- BSC support
- Fetch files from ipfs and github
- Test contracts on Goerli instead of xDai

New release

---

services/verification/src/utils.ts

- When fetching solc from GitHub, write it as a file in the directory specified by: `process.env.SOLC_REPO_TMP || "/tmp/solc-repo"`
- Partially fix typing in services/verification/src/utils.ts
- Fixes #374

Fetch solc to /tmp

---

scripts/setup.sh
services/ipfs/publish.sh
src/Dockerfile.monitor
src/Dockerfile.server

- server & monitor docker images optimization
- ipfs pinning temporary disabled
- CI docker-compose timeout extended to allow monitor restart

Small changes

---

.vscode/launch.json
package-lock.json
package.json
scripts/run_monitor.js
services/core/src/utils/CheckedContract.ts
services/core/src/utils/types.ts
services/core/src/utils/utils.ts
services/validation/src/ValidationService.ts
services/verification/src/services/Injector.ts
src/monitor/gateway.ts
src/monitor/monitor.ts
src/monitor/pending-contract.ts
src/monitor/source-fetcher.ts
src/monitor/util.ts
test/helpers/helpers.js
test/monitor.js
test/server.js

Changed Monitor's repo path. This also required minor changes in server and monitor tests. Fixes #402.

Monitor rewrite (corrected)

---

package.json
services/core/package.json
services/core/src/services/FileService.ts
services/core/src/sourcify-chains.json
services/verification/src/services/Injector.ts
services/verification/src/utils.ts

- Fix Infura id replacement
- Fix links in sourcify-chains file
- Remove fs-extra dependency that was causing build issues

Minor fixes

---

README.md

This PR addresses [recent questions](https://gitter.im/ethereum/source-verify?at=6044ba585d0bfb4e5891a87a) about Repository and how its content can be fetched.

Add Repository API documentation

---

services/verification/src/utils.ts

Check if external solc binary is valid by spawning a process that executes `solc --version` and checking its return status.
Fixes #423.

Validate solc before recompiling

---

services/core/src/utils/CheckedContract.ts
services/core/src/utils/types.ts
services/verification/src/services/Injector.ts
services/verification/src/utils.ts

Generate an ID at the beginning of injection process and add it to every log line. Close #427.
Minor logging improvements in other parts of the code.

Improve logging

---

scripts/partial_matches_cleanup.sh

- cleanup script that is used to remove partial matches for contracts that have been fully verified

Repository cleanup

---

README.md
src/server/controllers/VerificationController.ts
test/server.js
test/sources/contracts/ChildContract.sol
test/sources/contracts/ParentContract.sol
test/sources/metadata/child-contract.meta.object.json
ui-draft/src/components/Contract.tsx
ui-draft/src/components/verifier/Verifier.tsx
ui-draft/src/storage-provider.ts
ui-draft/src/styles/components/_collapsable-list.scss

Addressing the specifications in https://github.com/sourcifyeth/org/issues/46#issuecomment-817902847:
- Highlight what's missing with a red border
- Display all sources of one contract in a single list and distinguish between found and not found by displaying a visually not-so-attractive check or X symbol
- Add a dropdown to select the contract to be displayed (with an option that allows "all contracts" to be displayed)
Not addressing address autodetection because of unmet technical prerequisites.

UI Draft - enhancements

---

src/server/controllers/VerificationController.ts
test/server.js

What the title says. Also adds a test for this.
Closes #459 and potentially closes https://github.com/sourcifyeth/remix-sourcify/issues/54.

Return checksummed addresses from /verify and /check-by-address

---

ui-draft/src/components/Contract.tsx
ui-draft/src/components/verifier/Verifier.tsx

Checks whether the entered address is valid or empty; uploads to session only if so; otherwise just display the entered value. Persists the last valid input.

Fix input in UI draft (close #456)

---

environments/.env.latest
environments/.env.stable
services/core/src/sourcify-chains.ts

Switch to using custom nodes instead of Infura nodes for Goerli and Rinkeby.

Switch to custom nodes

---

.circleci/config.yml
scripts/monitor_ci.js
scripts/verification-e2e.js
scripts/verification-e2e.sh

Close #477.
- New part of staging/master workflow.
- Added to the nightly workflow.

Add verification-e2e test

---

services/core/src/chains.json
services/core/src/sourcify-chains.ts
services/core/src/utils/types.ts
services/verification/src/services/Injector.ts
services/verification/src/utils.ts
test/server.js
ui/package-lock.json
ui/src/common/constants.ts

- Updates chains.json from https://chainid.network/chains.json.
- Supports verification and monitoring of Arbitrum Rinkeby.
- Adds a new test case (contract with immutable variables on Arbitrum Rinkeby).
- Close https://github.com/ethereum/sourcify/issues/446

Add Arbitrum Rinkeby support

---

.circleci/config.yml
scripts/monitor_ci.js
scripts/monitor_ci.sh
scripts/verification-e2e.js
scripts/verification-e2e.sh

Add Ropsten and Goerli to chains where contracts are deployed in e2e tests (so far only Rinkeby was tested).
Supersedes #501.
@Jakic007 Is there a way to reduce code duplication in yaml?

E2E expansion

---

environments/.env.latest
environments/.env.stable
environments/ipfs.yaml

So far the ports were hardcoded. How should the variables be named?

Read IPFS port mappings from env vars

---

README.md
docs/architecture.md
services/core/src/chains.json
services/core/src/sourcify-chains.ts
ui/src/common/constants.ts

Added chain support. Also moved the chains list in README to below and added instructions for how to request chain support.

Support for Arbitrum, Ubiq, Oneledger Testnet

---

README.md
services/core/src/chains.json
services/core/src/sourcify-chains.ts
ui/src/common/constants.ts

**Boba Rinkeby:**
Contract: https://blockexplorer.rinkeby.boba.network/address/0xf71904bD3DCD3141BAF74AFD8F17281e207defe6/transactions
Source:
```
// SPDX-License-Identifier: LGPL-3.0-only
pragma solidity >=0.7.0 <0.9.0;
/// @title Create Call - Allows to use the different create opcodes to deploy a contract
/// @author Richard Meissner - <richard@gnosis.io>
contract CreateCall {
event ContractCreation(address newContract);
function performCreate2(
uint256 value,
bytes memory deploymentData,
bytes32 salt
) public returns (address newContract) {
// solhint-disable-next-line no-inline-assembly
assembly {
newContract := create2(value, add(0x20, deploymentData), mload(deploymentData), salt)
}
require(newContract != address(0), "Could not deploy contract");
emit ContractCreation(newContract); …
```

add boba l2 rinkeby and mainnet

---

README.md
services/core/src/chains.json
services/core/src/sourcify-chains.ts
ui/src/common/constants.ts

Add support for the following networks
- syscoin mainnet 
- Aurora mainnet and testnet 
Closes https://github.com/ethereum/sourcify/pull/624
Closes https://github.com/ethereum/sourcify/pull/612

Add support for new networks

---

ui-new/src/pages/Fetcher/Field.tsx
ui-new/src/pages/Fetcher/Result.tsx
ui-new/src/pages/Fetcher/index.tsx
ui-new/src/types.ts
ui-new/src/utils/api.tsx
ui-new/tailwind.config.js

Implement fetcher UI

---

.github/ISSUE_TEMPLATE/feature_project.yml

An issue template for requesting a verified project to be featured on the new sourcify website

Feature project Issue template

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

In continue to the discussion https://github.com/ethereum/sourcify/pull/526, we have launched mainnet and verified integration with the smart contracts.

adding oneledger mainnet

---

.vscode/launch.json
services/core/package-lock.json
services/core/package.json
services/core/src/utils/CheckedContract.ts
services/core/src/utils/types.ts
services/core/src/utils/utils.ts
services/validation/package-lock.json
services/validation/src/ValidationService.ts
services/verification/package-lock.json
services/verification/package.json
services/verification/src/services/Injector.ts
services/verification/src/utils.ts
src/config.ts
src/server/controllers/VerificationController-util.ts
src/server/controllers/VerificationController.ts
src/server/server.ts
test/server.js
ui/package-lock.json
ui/package.json
ui/src/constants.ts
ui/src/pages/Verifier/CheckedContractsView/CheckedContract/ChainAddressForm/Message.tsx
ui/src/pages/Verifier/FileUpload.tsx
ui/src/pages/Verifier/index.tsx

Extra files bytecode mismatch

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

- Add Chain Support for WAGMI 
- Verify mutable contracts

add-chain-11111

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

Hi yah for Crystaleum 💎 the changes requested are done now ready for merge

Add chain 103090

---

ui/package-lock.json
ui/package.json
ui/src/pages/Lookup/Field.tsx

Push to master to reschedule nightly builds in the CI

Hotfix: Fix the CI nightly builds

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

Add chain 420

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js
test/chains/deployContracts.js

Just added a new chains.json because the previous has already outdated.

Add godwoken mainnet

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

Support for (KEK): kekchain
chain ID: 420666
network ID: 1

Add chain 420666

---

ui/src/components/Button/index.tsx
ui/src/components/EtherscanLogo/index.tsx
ui/src/components/GitHubBranchSelect/index.tsx
ui/src/components/GitHubBranchSelect/style.css
ui/src/pages/LandingPage/index.tsx
ui/src/pages/Lookup/Result.tsx
ui/src/pages/Verifier/FileUpload.tsx
ui/src/pages/Verifier/GitHubInput.tsx
ui/src/pages/Verifier/RemoteInput.tsx

This new functionality does not add any new API on the server, it:
1) creates the "zip github url" starting from the repo name or the repo url
2) calls the `/input-files` API

Import from GitHub

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

Adds Oasis Emerald Mainnet chain 42262.

Add Oasis Emerald Mainnet

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

Adds Oasis Emerald Testnet chain 42261.

Add Oasis Emerald Testnet

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

Adds the confidential Oasis Sapphire Testnet chain 23295.

Add Oasis Sapphire Testnet chain

---

services/core/src/sourcify-chains.ts

Updating Celo Mainnet endpoint only

Update Celo Mainnet Endpoint

---

ui/src/featured.js

added ens to featured contracts

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

This PR adds support to Flare Chain (14)

Add Flare Mainnet Chain-14 support

---

services/core/src/sourcify-chains.ts
test/chains/chain-tests.js

Required - https://github.com/ethereum/sourcify/pull/911 (update for chains.json)

add-chain-2047

---

environments/server.yaml
services/core/src/chains.json
services/core/src/sourcify-chains.ts
services/verification/src/utils.ts
test/chains/chain-tests.js

- Update chains.json
- [Add Oasis Sapphire Mainnet chain](https://github.com/ethereum/sourcify/commit/417fa41cbfd0cf14be50b1247f4b7147e2a48eb3)
- Stringify compiler errors 
- Persist compiler binaries

Quick Release

---

src/server/controllers/VerificationController-util.ts
test/server.js

fix #947 
* add tests
* rename previous etherscan method to standard-json-input

handle etherscan contracts with multiple sources

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Add Wanchain Mainnet support. Test code is ready and tests all passed.

Add chain 888

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Add chain 7668 - The Root Network Mainnet

Add chain 7668

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Add chain 7701

---

.github/PULL_REQUEST_TEMPLATE/add-new-chain.md
.github/PULL_REQUEST_TEMPLATE/release.md
.github/pull_request_template.md
packages/bytecode-utils/package.json
packages/lib-sourcify/package.json
ui/public/index.html

- Quick release for updating Matomo configuration

Release v2.2.1

---

.github/PULL_REQUEST_TEMPLATE/release.md
packages/lib-sourcify/package.json
packages/lib-sourcify/src/lib/verification.ts
src/chains.json
ui/src/pages/LandingPage/index.tsx

- Updated chains.json
- Added `RPC_TIMEOUT` as env var in `lib-sourcify`
- Replace the video on the website

Release v2.2.2

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Adds support for chain 25925 - Bitkub Chain Testnet

Add chain 25925 (Bitkub Chain Testnet)

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Adds support for chain 96 - Bitkub Chain

Add chain 96 (Bitkub Chain)

---

src/sourcify-chains.ts
test/chains/chain-tests.js

The PR includes Rollux Testnet and removes a duplicated entry for Syscoin Tanenbaum.

Add Rollux

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Add Zilliqa EVM chain (32769)

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Add Kava Testnet Chain (2221)

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Add chain 111000

---

src/sourcify-chains.ts
test/chains/chain-tests.js

add chain 212

---

src/sourcify-chains.ts
test/chains/chain-tests.js

add new chain for 22776

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Add Arbitrum Nova 42170

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Taiko L3 chainId 167006

---

src/sourcify-chains.ts
test/chains/chain-tests.js
test/chains/sources/4337/multicall.metadata.json
test/helpers/assertions.js

Add chain 4337

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Add New Chain 369

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Thanks for reviewing our pull request to add a new support in Sourcify.
We have followed the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.
We checked the following items before submitting our pull request.

Add chain 10243 (Arthera Testnet)

---

src/sourcify-chains.ts
test/chains/chain-tests.js

Added support for Q networks

---

src/chains.json
src/config.ts
src/sourcify-chains.ts
test/chains/chain-tests.js

add Holesky support

---

src/sourcify-chains.ts
test/chains/chain-tests.js

added support for Haqq networks

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

Add Zeniq Chain Id 383414847825

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

Thanks for reviewing our pull request to add a new support in Sourcify.
We have followed the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.
We have checked the following items before submitting our pull request for a speedy review.
https://github.com/ethereum-lists/chains/pull/4083 is merged but [chains.json](../blob/staging/services/server/src/chains.json) is not synchronized yet so I've temporary added an `rpc`field to be able to deploy the test contract and make the new pass.
So I let you review this PR while waiting for [chains.json](../blob/staging/services/server/src/chains.json) to be automatically synchronized. Then I will remove the rpc field I added for test and I hope it should be ready.
---
- To see the specific tasks …

Add New Chain 10242

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

add lyra chain

---

ui/src/components/Toast/index.tsx

Fixed issue https://github.com/ethereum/sourcify/issues/1274

fixed Chromium Browsers Display Unwanted Whitespace on toast

---

services/server/src/server/controllers/verification/etherscan/etherscan.common.ts
services/server/src/server/controllers/verification/etherscan/session/etherscan.session.handlers.ts
services/server/src/server/controllers/verification/etherscan/session/etherscan.session.paths.yaml
services/server/src/server/controllers/verification/etherscan/stateless/etherscan.stateless.handlers.ts
services/server/src/server/controllers/verification/etherscan/stateless/etherscan.stateless.paths.yaml
services/server/test/etherscan.js
ui/src/pages/Verifier/EtherscanInput.tsx

Supported both in stateless, session + UI

Allow passing Etherscan API key as parameter in import from Etherscon

---

services/server/test/chains/chain-tests.js

Update test contract address for Arthera Testnet

---

package-lock.json
services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

Add Ozone Chain Mainnet

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

Add chain 710420

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

Add CrossFi Chain Testnet 4157

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

add-chain-202401

---

package-lock.json
services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

Add chain 1291

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

Add DEGEN chain

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.js

Add tangle mainnet

---

services/server/README.md

I had some spare time and wanted to fix this since I started, because I had problems running the server back then. I moved the development section to the top because that's what I usually expect to be at the top.

Fix server README to make local running clear

---

package-lock.json
services/database/migrations/20231109160023-sourcify.js
services/server/package.json
services/server/src/config/default.js
services/server/src/config/local-test.js
services/server/src/config/master.js
services/server/src/config/staging.js
services/server/src/server/server.ts
services/server/src/server/session.ts
services/server/test/server.js

Implement postgresql based session

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add MerlinChain

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add New Chain Aura Euphoria Testnet 6321

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

add xai mainnet and testnet

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add New Chains Bitlayer 200901,200810

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add chains Redstone (690) and Garnet (17069)

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

PlayFair Testnet Subnet

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

add Mantle Mainnet and Mantle Sepolia Testnet

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

The test new chain won't pass until the latest `chains.json` file is pulled, which includes the addition of the necessary chains and corresponding RPC endpoints.

Add Lamina1 chains

---

packages/lib-sourcify/src/lib/types.ts
packages/lib-sourcify/test/verification.spec.ts
services/server/test/verifier-alliance/constructor_arguments.json
services/server/test/verifier-alliance/partial_match.json
services/server/test/verifier-alliance/partial_match_2.json
services/server/test/verifier-alliance/partial_match_double_auxdata.json

https://github.com/verifier-alliance/database-specs/pull/11

Rename transformations keys following VerA schema

---

package-lock.json
renovate.json
services/server/package.json

Improves the configuration of Renovate and removes a deprecated dependency

Renovate maintenance

---

.circleci/continue_config.yml
.circleci/deploy_to_gcp.sh

Modifications required to deploy the images to GCP after the build step. 
I couldn't fully check if these are working fully, because it will run in the CI and well we need to run them on the CI.

Deploy images to GCP via CI

---

services/monitor/src/ChainMonitor.ts
services/monitor/src/DecentralizedStorageFetcher.ts
services/monitor/src/logger.ts

Support errors in Monitor logs

---

services/database/migrations/20240729112258-compiled_contracts-constraints.js

See https://github.com/verifier-alliance/database-specs/pull/12

add `compiled_contracts` artifacts constraints

---

services/monitor/README.md
services/monitor/src/DecentralizedStorageFetcher.ts
services/monitor/src/GatewayFetcher.ts
services/monitor/src/types.ts

Also add support for headers setting
See https://github.com/sourcifyeth/private-issues/issues/27

Implement gateways custom settings in Monitor

---

services/monitor/src/PendingContract.ts

Axios logs the whole request body in the error when a request fails. If the log payload is too big then GCP Cloud Run logs breaks. 
This PR removes the request body from the fetch error

Remove body from verification request error in monitor

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add Telcoin Network 2017

---

services/server/src/common/logger.ts

Log according to GCP severity format if running on GCP

---

services/server/src/common/logger.ts

Fix GCP log tracing format

---

services/database/README.md

Document how to verify deprecated chains in the script

---

services/server/src/server/controllers/controllers.common.ts

Server breaks with the request `https://staging.sourcify.dev/server/repository/contracts/partial_match/7000/static/..;/sign;@repo.sourcify.dev.dns.asdtaeta.xyz`

Fix unhandled getAddress errors inside safeHandler

---

.vscode/launch.json
services/monitor/.env.template
services/monitor/monitorChains.json
services/monitor/src/Monitor.ts
services/monitor/src/types.ts

Previous changes #1603 does not include the necessary changes to parse and replace the API keys. The PR adds that.

Fix monitor rpc authentication

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Adds chain 33111

---

scripts/check-s3-backup.mjs

`s3-backup-check` is failing too often because the s3 sync process is taking more than 24h to complete. As a workaround let's change the test to check not the contracts from the previous day, but from 2 days before.
This PR also include prettier fixes

Change `s3-backup-check` to check not the contracts from the previous day, but from 2 days before

---

services/server/src/server/services/storageServices/RepositoryV2Service.ts

Following the discussion: https://discord.com/channels/1160912737539473410/1160912738374127689/1287445616972140565
I don't see any downsides of this. If you think of something lmk.

Remove .sol extension in repositoryV2

---

services/server/README.md
services/server/src/config/default.js
services/server/src/config/master.js
services/server/src/config/migration.js
services/server/src/config/staging.js
services/server/src/server/cli.ts
services/server/src/server/services/StorageService.ts
services/server/src/server/services/storageServices/RepositoryV1Service.ts
services/server/src/server/services/storageServices/SourcifyDatabaseService.ts
services/server/test/helpers/ServerFixture.ts
services/server/test/integration/repository-handlers/files.spec.ts

See #1640
This PR also adds a list of all the available Sourcify configs in the readme file.

Use server public url in getTree instead of repositoryV1 url

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

chore: add new chain OORT Mainnet

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

chore: add new chain B2 Mainnet

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts
services/server/test/helpers/etherscanInstanceContracts.json

Add Polygon zkEVM Cardona Testnet chain

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

An `rpc` field was added for Metis Andromeda to use rpcs already available in `chains.json` and Alchemy's too. I haven't added a `rpc` field to Metis Sepolia config.

Add Metis Andromeda and Metis Sepolia

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Enabling Flare Mainnet Chain-14 support as advised here #1702 
Flare Mainnet Support was turned off as RPCs were failing but it should work now!

Enabling Flare Mainnet Chain-14 support

---

services/server/src/sourcify-chains.ts

Fix API keys on CircleCI

---

services/server/test/helpers/etherscanInstanceContracts.json

Add etherscan instance tests for Arbitrum Nova (42170)

---

services/server/src/chains.json
services/server/src/sourcify-chains-default.json
services/server/src/sourcify-chains.ts
services/server/test/chains/chain-tests.spec.ts

Fixes #1739 
Adds Mekong testnet: https://mekong.ethpandaops.io/

Add chain 7078815900

---

.vscode/launch.json

The debugger was broken for the Server Unit tests.

Don't run debugger on non-".ts" files

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Renamed and Enabled Kaia mainnet

---

services/server/src/server/controllers/verification/vyper/stateless/vyper.stateless.handlers.ts
services/server/src/server/controllers/verification/vyper/stateless/vyper.stateless.paths.yaml

This PR finalizes Vyper API's OpenAPI specifications and improves errors in the Vyper API handler.

Finalize vyper API: OpenAPI spec + error handling

---

services/database/scripts/ContractVerifier.mjs

Forgot to push this, should start from 1 instead of 3

Change creation tx script cold start to 1

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

add chain and test

---

packages/lib-sourcify/src/lib/AbstractCheckedContract.ts
packages/lib-sourcify/src/lib/SolidityCheckedContract.ts
packages/lib-sourcify/src/lib/VyperCheckedContract.ts
packages/lib-sourcify/src/lib/types.ts
packages/lib-sourcify/src/lib/validation.ts
packages/lib-sourcify/test/utils.ts
packages/lib-sourcify/test/validation.spec.ts
packages/lib-sourcify/test/verification.spec.ts
services/server/src/server/common.ts
services/server/src/server/controllers/verification/etherscan/etherscan.common.ts
services/server/src/server/controllers/verification/etherscan/session/etherscan.session.handlers.ts
services/server/src/server/controllers/verification/etherscan/stateless/etherscan.stateless.handlers.ts
services/server/src/server/controllers/verification/session-state/session-state.handlers.ts
services/server/src/server/controllers/verification/solc-json/session/solc-json.session.handlers.ts
services/server/src/server/controllers/verification/solc-json/stateless/solc-json.stateless.handlers.ts
services/server/src/server/controllers/verification/verification.common.ts
services/server/src/server/controllers/verification/verify/session/verify.session.handlers.ts
services/server/src/server/controllers/verification/verify/stateless/verify.stateless.handlers.ts
services/server/test/integration/etherscan.spec.ts

Implement Vyper support in session etherscan API

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add new chain 26100

---

services/database/dune/DuneTableClient.ts
services/database/dune/README.md
services/database/dune/SourcifyDuneSyncClient.ts
services/database/dune/fetchRows.ts
services/database/dune/index.ts

This PR implements a new `SourcifyDuneSyncClient` that generalizes batch synchronization for all the sourcify table to Dune.

Implement functionalities to allow sync in batch

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

add-chain-7200-839999

---

README.md

Added badges similar to https://github.com/ethereum/solidity README. 
Also updated descriptions.

Add Matrix, Discord badges, update Readme content

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

https://docs.sourcify.dev/docs/chain-support/ followed this link. Running tests locally seems to be OK, please let me know if anything wrong or missing.

Add Citrea Testnet

---

.circleci/scripts/publish_multiarch_images.sh
.circleci/scripts/publish_to_npm.sh
.circleci/scripts/test_new_chain_support.sh

Moves the function definition above the commands to fix the issue. Adds `set -e` lines to throw on errors

Fix not publishing to npm and throw on errors in the bash scripts

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add chain 2020: Ronin Mainnet

---

services/server/src/config/master.js

For moving forward with the next release.
Already added the new environment variables to GCP.

Enalbe writing to Verifier Alliance DB on production

---

services/server/src/apiv2.yaml

Fix misconfigured apiv2 OpenAPI configuration

---

renovate.json

Configure Renovate to only create one PR for both minor and patch updates

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add Zilliqa 2 proto-testnet chain

---

README.md

docs: replaced the discord link

---

packages/lib-sourcify/src/Verification/Verification.ts
packages/lib-sourcify/src/Verification/VerificationTypes.ts
services/server/src/server/apiv1/verification/etherscan/stateless/etherscan.stateless.handlers.ts
services/server/src/server/apiv1/verification/solc-json/stateless/solc-json.stateless.handlers.ts
services/server/src/server/apiv1/verification/verification.common.ts
services/server/src/server/apiv1/verification/verify/stateless/verify.stateless.handlers.ts
services/server/src/server/apiv1/verification/vyper/stateless/vyper.stateless.handlers.ts
services/server/src/server/services/StorageService.ts
services/server/src/server/services/storageServices/AbstractDatabaseService.ts
services/server/src/server/services/storageServices/AllianceDatabaseService.ts
services/server/src/server/services/storageServices/RepositoryV1Service.ts
services/server/src/server/services/storageServices/RepositoryV2Service.ts
services/server/src/server/services/storageServices/SourcifyDatabaseService.ts
services/server/src/server/services/utils/database-util.ts
services/server/src/server/services/utils/util.ts

Use VerificationExport for storeVerification methods of storage services

---

services/server/test/unit/utils/contract-creation-util.spec.ts

Since avax API stopped suporting Ethereum Mainnet for creator txHash, we provide an avalanche contract

Fix avax API test

---

packages/lib-sourcify/README.md

IMHO the previous documentation was too long and contain a lot of unnecessary information. 
I rewrote it by removing many parts and making it more concise. Let me know what you think.

Update update lib sourcify docs

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Added Zircuit Garfield Testnet

---

.circleci/scripts/publish_to_npm.sh
package-lock.json
packages/compilers-types/.gitignore
packages/compilers-types/package.json
packages/compilers-types/src/CompilationTypes.ts
packages/compilers-types/src/SolidityTypes.ts
packages/compilers-types/src/VyperTypes.ts
packages/compilers-types/src/index.ts
packages/compilers-types/tsconfig.json
packages/compilers/package.json
packages/compilers/src/lib/solidityCompiler.ts
packages/compilers/src/lib/vyperCompiler.ts
packages/lib-sourcify/package.json
packages/lib-sourcify/src/Compilation/AbstractCompilation.ts
packages/lib-sourcify/src/Compilation/CompilationTypes.ts
packages/lib-sourcify/src/Compilation/SolidityCompilation.ts
packages/lib-sourcify/src/Compilation/VyperCompilation.ts
packages/lib-sourcify/src/Validation/SolidityMetadataContract.ts
packages/lib-sourcify/src/Validation/processFiles.ts
packages/lib-sourcify/src/Verification/Transformations.ts
packages/lib-sourcify/src/Verification/Verification.ts
packages/lib-sourcify/src/Verification/VerificationTypes.ts
packages/lib-sourcify/src/index.ts
packages/lib-sourcify/test/Compilation/SolidityCompilation.spec.ts
packages/lib-sourcify/test/Validation/SolidityMetadataContract.spec.ts
packages/lib-sourcify/test/Verification/Verification.spec.ts
packages/lib-sourcify/test/utils.ts
scripts/release/release.sh

Closes https://github.com/ethereum/sourcify/issues/1958

Add `compilers-types` package

---

services/server/src/openapi.yaml
services/server/src/server/apiv2/jobs/jobs.routes.ts
services/server/src/server/apiv2/verification/verification.routes.ts
services/server/src/server/services/VerificationService.ts
services/server/test/integration/apiv2/jobs.spec.ts
services/server/test/integration/apiv2/verification/verify.json.spec.ts

Enabling this again because the release is done

Revert "Disable v2 verification and job status endpoints and do not run Piscina workers (#2061)"

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Added chain 5330: Superseed Mainnet

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Added chain 21000000: Corn Mainnet

---

services/server/src/common/logger.ts

I noticed that logs from compilers package were not properly formatted on GCP.

Set compilers package logger inside server

---

services/server/src/common/async-context.ts
services/server/src/server/server.ts
services/server/src/server/services/VerificationService.ts
services/server/src/server/services/workers/verificationWorker.ts
services/server/src/server/services/workers/workerTypes.ts

Set logLevel and inject traceIds in verificationWorker threads

---

services/server/src/openapi.yaml
services/server/src/server/apiv1/routes.ts
services/server/src/server/apiv1/verification/etherscan/session/etherscan.session.paths.yaml
services/server/src/server/apiv1/verification/etherscan/stateless/etherscan.stateless.paths.yaml
services/server/src/server/apiv1/verification/session-state/clear.session-state.paths.yaml
services/server/src/server/apiv1/verification/session-state/data.session-state.paths.yaml
services/server/src/server/apiv1/verification/session-state/input-contract.session-state.paths.yaml
services/server/src/server/apiv1/verification/session-state/input-files.session-state.paths.yaml
services/server/src/server/apiv1/verification/solc-json/session/solc-json.session.paths.yaml
services/server/src/server/apiv1/verification/solc-json/stateless/solc-json.stateless.paths.yaml
services/server/src/server/apiv1/verification/verify/session/verify.session.paths.yaml
services/server/src/server/apiv1/verification/verify/stateless/verify.stateless.paths.yaml
services/server/src/server/apiv1/verification/vyper/stateless/vyper.stateless.paths.yaml
services/server/src/server/server.ts

Deprecate API v1

---

services/server/src/chains.json
services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

- Turns off Rollux Mainnet (570)
- Updates chains.json
- Switches to chains.json rpcs on Telos instead of custom in sourcify-chains.json.

Failing chains

---

services/server/test/integration/apiv2/verification/verify.etherscan.spec.ts

Skip Etherscan tests for external PRs

---

packages/lib-sourcify/src/Verification/Transformations.ts

Add support for zeroed-out placeholders to accept bytecodes from the database

---

packages/lib-sourcify/src/Verification/Verification.ts
services/server/test/integration/apiv2/verification/verify.json.spec.ts

Remove creatorTxHash's undefined assignment when creation match fails

---

services/database/README.md
services/server/README.md
services/server/src/config/default.js

See https://github.com/sourcifyeth/private-issues/issues/39

Update database and server README files

---

packages/lib-sourcify/src/SourcifyChain/SourcifyChainTypes.ts
services/server/.env.dev
services/server/src/server/services/utils/contract-creation-util.ts
services/server/src/sourcify-chains-default.json
services/server/test/unit/utils/contract-creation-util.spec.ts

Closes #2172 
already added the key to CI and staging and production deployments

Add contract creation transaction fetching via VeChain Stats

---

services/server/src/server/server.ts

Sets the CORS middleware as the very first, otherwise things like API validation errors will not have CORS headers and browser applications will fail to return meaningful errors.

Move CORS settings as the first middleware

---

services/server/src/server/services/VerificationService.ts
services/server/src/server/services/storageServices/AbstractDatabaseService.ts

Improve error logging for errors in `updateExistingVerifiedContract` 

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add chain 2206132

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add chain 210425

---

services/server/src/server/services/VerificationService.ts
services/server/test/unit/VerificationService.spec.ts

Fixes #2207
The above issue is caused by wrongly chaining the promises in the `VerificationService`. It wasn't handling any unexpected errors thrown by the `verificationWorker` before.

Fix VerificationService to handle errors thrown by `workerPool.run`

---

packages/lib-sourcify/src/SourcifyChain/SourcifyChain.ts
packages/lib-sourcify/src/SourcifyChain/SourcifyChainTypes.ts
services/server/src/server/services/utils/contract-creation-util.ts
services/server/src/sourcify-chains-default.json
services/server/src/sourcify-chains.ts

Rpcs housekeeping

---

services/server/src/apiv2.yaml
services/server/src/server/apiv2/middlewares.ts
services/server/test/unit/apiv2/middlewares.spec.ts

See https://github.com/ethereum/sourcify/issues/2247#issuecomment-3155878775

Compiler version validation

---

services/database/migrations/20250828092603_add_signature_tables.sql
services/database/sourcify-database.sql
services/server/package.json

Add migrations for signature tables

---

services/database/migrations/20250828092603_add_signature_tables.sql
services/database/sourcify-database.sql

I will rollback the migration and reapply on staging after merging

Add constructor type to signature tables migration

---

services/database/package.json
services/server/package.json
services/server/src/server/signature-api/openchain.handlers.ts
services/server/test/integration/signature-api/openchain.spec.ts

Properly handle filter query parameter in OpenChain handlers

---

services/server/src/sourcify-chains-default.json
services/server/test/chains/chain-tests.spec.ts

Add chains 1135, 130, 167000
