- injector.js
- monitor.js
This was not tested as I could not run the docker script.
But this could work already or at least provide a basis to support metadata generated via the litteral content option
> add support for litteral source

- public/index.html
IPNS is quite slow and provides bad UX due to this bug: https://github.com/ipfs/go-ipfs/issues/3860
the current alternative is quite centralized.
Providing the content via ENS could be an option - currently just the content hash is manually set there - but in the future this could be a smart contract where multiple parties must agree on the content and make it more decentralized this way.
Draft PR for now as the linking experience in brave is quite bad: https://youtu.be/hOmYC3CIseA
Will file a bug there later. 
Just entering verificat.eth/ in the URL bar works - but the link opens one extra tab
> Add ENS link

- .env.latest
- ui/App.js
#66 incorrectly checked for process.env.TESTING in the React script. The NODE_ENV setting is the only environment variable visible there.
> Display localhost:8545 as option in staging UI

- src/injector.ts
- src/utils.ts
- test/injector.js
- test/utils.js
**PR targets #96**
#95 
Adds logic and tests for tolerant bytecode comparison when injecting. 
If the bytecodes match up to but not including the metadata component, the sources and metadata are saved to a fallback folder called `partial_matches` as below:
**Example**
```
repository/
partial_matches/
goerli/
0x26EA1B6a99F491B5700D104CaD55c6Db07AAAFA2/
sources/
metadata.json
```
> Save contracts when metadata does not match

- package-lock.json
- package.json
- src/injector.ts
- src/monitor.ts
- src/server.ts
- src/utils.ts
- test/injector.js
- test/monitor.js
- test/server.js
- test/sources/pass/simple.literal.js
- test/utils.js
#11 
Adds a conventional server logging service to manage output. All messages now look something like:
```
{"name":"Injector","hostname":"Users-MacBook-Air.local","pid":81065,"level":30,"loc":"[RECOMPILE]","fileName":"/Users/cgewecke/code/ef/ts/contracts/Simple.sol","contractName":"Simple","version":"0.6.0+commit.26b70077","msg":"Recompiling","time":"2020-03-16T02:47:21.633Z","v":0}
{"name":"Injector","hostname":"Users-MacBook-Air.local","pid":81065,"level":30,"chain":"localhost","address":"0xbcf41f450d9fEe5FB2d3FD51De033F70A176A9eB","msg":"Retrieving contract bytecode address","time":"2020-03-16T02:47:27.531Z","v":0}
```
...so they can be easily searched / or processed for errors.
Error logs have an `err` and `msg` field` as below:
``` …
```
> Add json parse-able server logging

- src/injector.ts
- test/helpers/helpers.js
- test/injector.js
- test/sources/pass/simple.bzzr0.js
- test/utils.js
Part of #37 and should also make  #6 close-able.
I accidentally removed bzzr0 hash support from the injector during the initial refactor. 
PR restores it and adds tests for injecting bytecodes with swarm hashes.
> Restore injector support for bzzr0

- src/injector.ts
Fixes currently broken UI on staging...the React app expects the injector to pass back a list of addresses it saved.
> Return saved addresses from injector (for UI)

- package.json
- scripts/run_monitor.sh
#108 
@edisinovcic I think this is right but just double-checking... the only place that runs it is here?
https://github.com/ethereum/source-verify/blob/ede2477cf14c090f862011e2697fc668c448fe0b/src/Dockerfile.monitor#L9
> Remove run_monitor.sh

- src/server.ts
- test/server.js
- test/sources/metadata/simple.meta.object.json
Resolves issue reported in #6 where metadata is being reformatted as a normal JSON file before being submitted.  This is a natural thing for people to do...
> Accept JSON formatted metadata in server

- package.json
- scripts/run_monitor.js
- src/Dockerfile.monitor
- src/Dockerfile.server
@cgewecke dist not flattened in my case was because of the some leftover cache. Reverting to previous version. So everyfile is now located in dist/ folder as expected.
I'm merging this fix now.
> Removing cache, fixing dist path not flattened

- src/server.ts
- src/utils.ts
- test/server.js
- ui/App.js
Adds some server tests following on #123. 
There are a few logic changes because we weren't exiting the flow correctly in some cases. 
For example, when an address was discovered successfully, we didn't return immediately after response, causing a second response and express to complain about resetting the headers.
When an address was submitted without files, the error was about missing req.files.files (but the files are optional now.) 
A little logic has been re-worked for the error cases as well by wrapping in try/catch blocks etc.
> Add unit tests for address-only server submissions (plugin)

- src/injector.ts
- src/server.ts
- test/server.js
- ui/App.js
Should fix #128. 
`verificationstaging`'s link resolves the address component of the link correctly for address-only submissions. This can be checked with inputs:
+ network: Ropsten
+ address: 0xEB6Cf7952c666F81f1a5678E80D4fC5Ce3a7bF0b 
It's currently broken for `injector.inject` because it's returning `Match[]` and is passed to `Promise.all` which wraps it in another array.  
Per [gitter comment][1]) there's also a problem with the link root, which looks like this 
```
http://verificationstaging.komputing.org/contract/goerli/0x961FaFF29974DbF4191F993d4B68Ce1cB73208d8/
```
instead of 
```
http://contractrepostaging.komputing.org/contract/goerli/0x961FaFF29974DbF4191F993d4B68Ce1cB73208d8/
```
Have updated the `href` to look like this: (Think we'll need to merge and build this to see if it …
> Make injector.inject return match object instead of array

- src/injector.ts
- src/monitor.ts
- src/utils.ts
- test/monitor.js
- test/server.js
Resolves #113 
Up to now, sources detected by the Monitor haven't been recompiled before saving. 
PR adds logic to:
+ cache sources listed in the metadata manifest as the monitor acquires them
+ submit sources to the Injector for validation & repository writes.  
Also:
+ Adds an `offline` mode to the Injector class so it can be instantiated without opening connections to remote chain providers
+ Adds logic to let the Monitor submit bytecode it's already gotten from the chain to `Injector.inject`
> Recompile monitor-detected sources

- src/monitor.ts
Adding catch blocks so errors get logged and retrieval doesn't break the monitoring service.
Solving https://github.com/ethereum/sourcify/issues/176
> Adding error catch blocks on source, metadata and block retreivals

- scripts/monitor_ci.sh
Monitor E2E CI has [been failing][1] during its contract deployment step in a way that suggests it's not able to read the `INFURA_ID` env variable. The logic that checked the repo in a loop has been swallowing the error.
Reverting a bit here to the original version to see if we can get it working again...
I've restored `INFURA_ID` to the CI settings for the moment.
[1]: https://app.circleci.com/pipelines/github/ethereum/sourcify/469/workflows/28a97ebb-1da3-4a29-abfa-9587ac98ffd7/jobs/1862
> Simplify monitor nightly script / add longer timeout

- src/injector.ts
- src/monitor.ts
- src/server.ts
- src/sourcify.ts
- src/utils.ts
- test/injector.js
- test/monitor.js
- test/server.js
- test/sourcify.js
For every metadata file original name is preserved through verification and saved like that in the repository.
This works for every module: UI verification, CLI verification, API requests to server and monitor fetch.
FindByAddress method also recognizes metadata files with different names.
> original metadata name preserved

- src/Dockerfile.server
- src/chains.json
- src/injector.ts
Added dappnode endpoints to chains.json that are used if infuraID is not provided.
Docker image for server is now node-alpine which reduced it size for 1/3.
> server can use dappnode instead of infura

- environments/.env.latest
- environments/.env.stable
- environments/.env.testing
- environments/ipfs-monitoring.yaml
- environments/monitor-monitoring.yaml
- environments/repository-monitoring.yaml
- environments/s3-monitoring.yaml
- environments/server-monitoring.yaml
- environments/ui-monitoring.yaml
Adding loki driver to docker compose so that logs can be redirected to loki and shown in grafana.
> Adding loki driver to docker logs

- .circleci/config.yml
- .vscode/launch.json
- package.json
- services/core/src/chains.json
- services/core/src/utils/utils.ts
- services/verification/src/services/Injector.ts
- src/monitor/monitor.ts
- ui/src/common/constants.ts
Added xDai support on both backend and frontend. This was suggested in https://github.com/ethereum/sourcify/issues/277. There was code duplication with listing available chains in monitor and injector; this was solved by adding a new method to core/utils. A new script was added to package.json that enables building with lerna.
> Add xdai support; refactor chain retrieval; add build:lerna

- services/ipfs/publish.sh
This will provide statistics on how many contracts are verified on each of supported chains.
It is updated every hour and output is written inside the `stats.json` file which is located inside the root of the repository.
Anyone is able to fetch it by using this URL: https://contractrepo.verificationstaging.shardlabs.io/stats.json
> verification statistics

- README.md
also removed the wasteful slashes from the URLs
PS: we should also make the contractrepo a sourcify.dev subdomain for consistency
> Use sourcify URL instead of komputing

- README.md
- docs/api/server/getAnyByChainAndAddress.md
- docs/api/server/getAnyTreeByChainAndAddress.md
- docs/api/server/getByChainAndAddress.md
- docs/api/server/getTreeByChainAndAddress.md
- services/core/src/services/FileService.ts
- services/core/src/utils/types.ts
- src/server/controllers/FileController.ts
Fetch partial if full match not available: https://github.com/ethereum/sourcify/issues/321
- FileController had two endpoints:
- /tree/:chain/:address
- /:chain/:address
- Added two more that return partial matches if full not found (the return object contains the property `status` indicating whether it was a full or a partial match):
- /tree/any/:chain/:address
- /any/:chain/:address
- Refactored FileController to reduce code duplication.
Possible discussion points:
- url path choice (/any)
Solves:
* https://github.com/sourcifyeth/remix-sourcify/issues/27
> Fetch partial matches if full not available

- README.md
- services/core/src/chains.json
- ui/src/common/constants.ts
Now supporting:
- Matic Mainnet
- Mumbai Testnet
- Binance Smart Chain Mainnet
- Binance Smart Chain Testnet
Updates are reflected in the documentation and the UI (it doesn't look as appealing as before because there are 10 options in the dropdown; however this UI will soon be history)
> Support Matic and Binance

- Sourcify.postman_collection.json
- docs/api/server/verification1/verify.md
- docs/api/server/verification2/exchange-object.md
- docs/api/server/verification2/verify-validated.md
- services/core/src/utils/CheckedContract.ts
- services/core/src/utils/types.ts
- services/verification/src/services/Injector.ts
- services/verification/src/utils.ts
- src/server/controllers/VerificationController-util.ts
- src/server/controllers/VerificationController.ts
- test/server.js
- User may specify to fetch missing sources. This is done by providing a `fetch` property set to `true` or `"true"`. See docs on how exactly this may be achieved in API v1 and API v2.
- If possible, source fetching is first attempted from GitHub, then from IPFS.
- If a solc version is not present, its fetching is first attempted from [the Github repo](https://github.com/ethereum/solc-bin/tree/gh-pages/linux-amd64).
> Improve fetching

- test/server.js
- test/testcontracts/1_Storage/1_Storage.sol
- test/testcontracts/1_Storage/metadata.json
- Switch to using a Goerli contract in the mocha tests to reduce execution time.
- Fixes #356.
> Switch mocha tests to Goerli

- services/core/src/sourcify-chains.json
The sourcify-chains.json was left in a state that made it impossible for the current Injector implementation to use the dappnode data.  This is now fixed by correcting the json structure.
> Fix fullnode-dappnode usage

- Sourcify.postman_collection.json
- docs/api/server/verification1/verify.md
- docs/api/server/verification2/exchange-object.md
- docs/api/server/verification2/verify-validated.md
- environments/.env.latest
- environments/.env.stable
- scripts/run_monitor.js
- services/core/src/utils/CheckedContract.ts
- services/core/src/utils/types.ts
- services/verification/src/services/Injector.ts
- src/monitor/monitor.ts
- src/server/controllers/VerificationController-util.ts
- src/server/controllers/VerificationController.ts
- test/server.js
- Add fetching timeout.
- Use IPFS_URL and FETCH_TIMEOUT env vars.
- When using local IPFS fetching: `IPFS_URL=http://127.0.0.1:8080/ipfs/`
- If no IPFS_URL provided: defaults to `https://ipfs.infura.io:5001/api/v0/cat?arg=`
- Make fetching from GitHub and IPFS the default behavior.
- Make monitor use the IPFS_URL variable (after a force-push)
Discussion point: Should IPFS_URL be encapsulated within config.ts or used directly from process.env?
> Make fetching the default behavior

- .vscode/launch.json
- package-lock.json
- package.json
- scripts/run_monitor.js
- services/core/src/utils/CheckedContract.ts
- services/core/src/utils/types.ts
- services/core/src/utils/utils.ts
- services/validation/src/ValidationService.ts
- services/verification/src/services/Injector.ts
- src/monitor/gateway.ts
- src/monitor/monitor.ts
- src/monitor/pending-contract.ts
- src/monitor/source-fetcher.ts
- src/monitor/util.ts
- test/helpers/helpers.js
- test/monitor.js
- test/server.js
- Restructure the Monitor component
- Dynamically adapt the time between two block fetchings
- Enable monitoring old blocks (via env vars)
- Enable monitor mocha testing
- Changes to services/verification/src/services/Injector.ts (add an offline version of the static constructor)
- Pending:
- Squash to a single commit
- Fix #385
- Fix #387
- Fix #399
> Monitor improvement

- docs/api/server/verification1/check-by-addresses.md
- src/server/controllers/VerificationController.ts
- test/server.js
- ui/package-lock.json
- ui/package.json
- ui/src/api/verifier.ts
- ui/src/common/constants.ts
- ui/src/components/verifier/Verifier.tsx
- ui/src/utils/index.ts
So far, when pasting an address in the UI, the user would be informed of just whether the address has already been verified on any of the chains supported by Sourcify. With this pull request, the user will be provided with a list of chains where the address is verified (handled possibility: same address on multiple chains). Every chain name in the list also holds a link to the contract's sources in the repo. This was achieved by enriching the body retrived by /check-by-addresses with an additional `chains` property in case of a full match.
Also:
+ Refactor old front-end code (chain retrieval, message generation)
+ Update tests and docs
+ The `serve` script was overwriting clipboard with localhost:1234. This is now prevented with the `--no-clipboard` flag.
> Improve how address checking is reported to the user

- src/Dockerfile.monitor
- src/Dockerfile.server
- alpine images were not able to run any solc from 0.7.6
> Hotfix for latest solc-bin executables

- src/monitor/gateway.ts
- src/monitor/pending-contract.ts
- src/monitor/source-fetcher.ts
- src/monitor/util.ts
- test/monitor.js
- test/server.js
Reduce congestion in source fetching by:
- separating fetching to different queues (not really queues, basically arrays iterated over), one per each gateway (ipfs, swarm)
- removing unnecessary scheduled fetchings (e.g. a source is retrieved from ipfs -> can be deleted from the swarm queue)
Make cleanup implementation clearer.
> Monitor2.2

- services/core/package-lock.json
- services/core/package.json
- services/core/src/services/FileService.ts
- services/core/src/sourcify-chains.ts
- services/verification/src/services/Injector.ts
- test/server.js
- test/testcontracts/1_Storage/1_Storage-modified.sol
- test/testcontracts/1_Storage/metadata-modified.json
If there is an earlier partial match of a contract, it is deleted when it gets fully matched in a later process of verification. Sending a verification response to the user does not wait for the deletion process to finish.
The default chains.json specifies a Görli RPC which has lately had stability issues (often not available). The RPC is overriden with a more stable one in sourcify-chains.json. This was done because tests couldn't pass otherwise.
> Delete partial on full match

- README.md
- services/core/src/sourcify-chains.ts
- test/server.js
- test/sources/metadata/withImmutables2.meta.object.json
- ui-draft/src/common/constants.ts
- ui/src/common/constants.ts
Support the verification of contracts deployed on POA Network Sokol. Support is added for:
- API verification
- old UI verification
- new UI-draft verification
- automatic monitor verification
This PR updates README.md and adds a new mocha test.
Closes https://github.com/ethereum/sourcify/issues/451.
> Add Sokol support

- README.md
- services/core/src/utils/types.ts
- services/verification/src/services/Injector.ts
- test/monitor.js
- test/server.js
- Close #435.
- The arguments are provided as a text file with hex digits called `constructor-args.txt`, at the same level as `metadata.json`.
- The hex string is "0x" prefixed.
- This stores only the arguments of constructors of contracts using immutable variables.
> Make constructor arguments available in the repo

- services/verification/src/services/Injector.ts
- test/monitor.js
- test/server.js
- test/sources/metadata/withoutMetadataHash.meta.object.json
- test/sources/pass/withoutMetadataHash.js
- Closes #465.
- Contracts without bytecode hash (metadata hash embedded at the end part of the contract) can not be marked as full matches any longer.
- Tests the behavior with two new tests (one in server.js, one in monitor.js; the monitor test just expects monitor not to fail in case of a contract without bytecode hash).
> Mark contracts without bytecode hash as partial matches

- services/core/src/utils/types.ts
- services/verification/src/services/Injector.ts
- services/verification/src/utils.ts
- test/server.js
- test/sources/contracts/UsingLibrary.sol
- test/sources/metadata/using-library.meta.object.json
Placeholders in the recompiled bytecode are replaced with addresses from corresponding locations in the actual deployed bytecode. Similarly to `constructor-args.txt`, stored under `library-map.json`.
> Add support for contracts with library address placeholders

- README.md
- docs/api/server/getContractsByChain.md
- services/core/src/services/FileService.ts
- services/core/src/sourcify-chains.ts
- services/core/src/utils/types.ts
- services/verification/src/services/Injector.ts
- services/verification/src/utils.ts
- src/server/controllers/FileController.ts
- ui/src/common/constants.ts
Per conversation on gitter, this PR includes 2 changes:
- It adds support for Telos EVM testnet and mainnet (mainnet going live in coming weeks)
- It adds a new API route for getting a list of contract addresses for a given chain so available contracts are discoverable
> Adding contracts route and Telos networks

- environments/.env.stable
The old port was occupied, so a new one was chosen. Basically a hotfix of https://github.com/ethereum/sourcify/pull/513.
Some checks are failing because there are issues with the Ropsten Geth node, in use by both monitor and server.
> Replace IPFS_LIBP2P_EXTERNAL_PORT in .env.stable

- services/ipfs/entrypoint.sh
The previous `server` profile disables localhost discovery. According to [docs](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#profiles) this is for when running a server but breaks things when dockerized. Change should make the ipfs node reachable over the docker network and also from outside.
See #495
> Fix dockerized ipfs nodes unreachable

- services/validation/src/ValidationService.ts
- services/verification/src/utils.ts
Previously the backup RPC's were not being used and only the first RPC. I.e. when our geth node is down, it does not fallback to Alchemy API.
> Fix only 1 network RPC getting called

- services/core/src/sourcify-chains.ts
Blockscout to Etherscan SUFFIX, REGEX edit. 
Reason : Blockscout deprecated.
@Jakic007
> ETHERSCAN_SUFFIX, REGEX for Avalanche Network

- README.md
- services/core/src/sourcify-chains.ts
- ui/src/common/constants.ts
Adds optimistic mainnet to the supported networks in addition to optimistic kovan which was merged in #550 
Pending optimistic mainnet regenesis scheduled for 11th November after which we can provide the sources off OE mainnet as well. 
Resolves #352
> Add support for Optimistic Mainnet network 

- docs/api/server/verification1/check-all-by-addresses.md
- services/core/src/services/FileService.ts
- services/verification/src/services/VerificationService.ts
- src/server/controllers/VerificationController.ts
- test/server.js
- ui/src/api/verifier.ts
- ui/src/components/verifier/Verifier.tsx
Currently the endpoints /check-by-address and /checkByAddress that look if an address is verified in any of the chains in the Sourcify repo only look for full matches. When a contract address that is partially matched is input, the endpoint returns that it is not found.
This PR introduces a new API route (`/check-all-by-address` or `/checkAllByAddress`)  for fetching all matches for a verified addresses. The response returned by this route will look like this:
```json
{
"address": "0x0A67477639a71bf98528280D3724f465A1814740",
"chainIds": [
{
chainId: '1',
status: 'perfect'
}
{
chainId: '5',
status: 'partial'
}
]
},
```
With this, we can easily display on the frontend which chains have a partial or full verification of a contract 
Closes #593
> checkByAddress does not return partial matches

- services/ipfs/entrypoint.sh
On bf7bbab the profile of the server profile of the ipfs node
was removed to allow "local discovery" but it seems it is unrelated to
the networking issues at the time. Announcing the public ip's should
have been sufficient.
Instead the ipfs node started receiving the error:
"ignoring incoming dht message while not in server mode".
Revert back to the server profile.
> Revert IPFS profile to server

- services/core/src/sourcify-chains.ts
- test/chains/chain-tests.js
I have a local build setup for sourcify and have successfully deployed the standard contract to the MultiVAC mainnet following the instructions provided.
The test passes, **with the caveat** that until the chains.json has been synced to the current chainid.network/chains.json in the main repository -- this can't be merged.
I manually synced the latest into my fork to ensure the tests pass.
> Add MultiVAC Mainnet (62621)

- environments/.env.dev
- environments/.env.latest
- environments/.env.stable
- scripts/setup.sh
- services/core/src/services/FileService.ts
- services/core/src/utils/CheckedContract.ts
- services/ipfs/entrypoint.sh
- services/ipfs/publish.sh
- services/verification/package-lock.json
- services/verification/package.json
- services/verification/src/services/Injector.ts
- src/monitor/source-fetcher.ts
- test/monitor.js
- test/sourceFetcher.js
Instead of `ipfs add`ing the whole repo regularly, add the files to ipfs incrementally as they are being added to the repo via IPFS' Mutable File System (MFS) abstraction. Also revert using Filestore and implicitly the `--raw` leaves encoding, which broke the served CIDs of the files in the repo. Remove `IPFS_URL` var and introduce `IPFS_GATEWAY` + `IPFS_API`. Don't prune `--all` Docker images to avoid building new images when no related file was changed.
> Add contract files to IPFS incrementally 

- services/core/src/sourcify-chains.ts
The explorer for the network was moved to a different url. PR updates it for the contract fetch address.
I couldn't find any instructions for that case, and named the branch as `add-chain-{chainId}`, so tests for new networks could run. Will update as required, if updates should be made in other way
> Chain 8217 - update contract fetch address

- services/core/src/sourcify-chains.ts
The explorer for the network was moved to a different url. PR updates it for the contract fetch address.
> Chain 1001 - update contract fetch address

- services/core/src/sourcify-chains.ts
- services/verification/src/utils.ts
We are in the process of deprecating [subnet-explorer-api](https://subnet-explorer-api.avax.network) and moving all functionality over to our new glacier-api. This PR updates the contract creation data fetch address.
> Update Avalanche subnet creation data fetch address

- services/core/src/sourcify-chains.ts
- test/chains/chain-tests.js
The new [Sapphire 0.4.0](https://github.com/oasisprotocol/sapphire-paratime/releases/tag/v0.4.0-testnet) supports unencrypted calls. Sourcify test contract has now been deployed with an unencrypted transaction and checks for immutable contracts should correctly pass.
Related: #895
> Add Oasis Sapphire Testnet chain again

- services/core/src/sourcify-chains.ts
- test/chains/chain-tests.js
Adds the confidential Oasis Sapphire Mainnet chain 23294.
Merge after the [Sapphire Mainnet endpoint](https://sapphire.oasis.io/) is officially announced.
> Add Oasis Sapphire Mainnet chain

- .vscode/launch.json
- package-lock.json
- package.json
- packages/lib-sourcify/src/lib/CheckedContract.ts
- src/server/controllers/VerificationController.ts
- test/server.js
Since the tests are sometimes failing on CircleCI because of being rate limited by the public ipfs.io gateway, we instead spin up a local nodejs ipfs gw in tests.
> Use a local ipfs gw on tests

- packages/lib-sourcify/src/lib/solidityCompiler.ts
- packages/lib-sourcify/test/functions.spec.ts
* download the solcjs binary like the amd one
* use the downloaded binary through setupMethods
* check existing binaries before downloading new one
> Default SolcJs compiler

- src/server/controllers/VerificationController.ts
- src/server/server.ts
Since the bodyParser, was set before the cors in server.ts, the response will have wrong CORS when body size limit is hit.
Move the cors settings above bodyParser.
Also add conditional CORS settings as session requires cookies and "*" CORS is not possible. Remove the individual cors() middleware on every session route in VerificationController.
TODO:
~~- [ ] Add informative message on the UI when HTTP status is `413`~~
> Fix CORS error on req too large

- packages/lib-sourcify/src/lib/solidityCompiler.ts
- packages/lib-sourcify/test/functions.spec.ts
> Handle solc links in repo when fetching compiler

- packages/lib-sourcify/src/lib/verification.ts
Instead of replacing the library using a regular expression, use split.
Thanks to @hellobloc and @samczsun for reporting the problem. I will add more information after we deploy.
> Change how addLibraryAddresses replaces the library addresses from the recompiled bytecode

- packages/lib-sourcify/README.md
- packages/lib-sourcify/src/lib/types.ts
- packages/lib-sourcify/src/lib/verification.ts
- packages/lib-sourcify/test/utils.ts
- packages/lib-sourcify/test/verification.spec.ts
- src/monitor/monitor.ts
- src/server/controllers/VerificationController-util.ts
- src/server/controllers/VerificationController.ts
- src/server/services/RepositoryService.ts
- src/server/services/VerificationService.ts
- ui/src/pages/Verifier/CheckedContractsView/CheckedContract/ChainAddressForm/index.tsx
- ui/src/types.ts
* remove verification through simulation
> Quick Release

- ui/src/pages/Verifier/CheckedContractsView/CheckedContract/ChainAddressForm/index.tsx
See #936 for details.
Instead of verifying if an address is valid, tries to checksum it
> Fix how the ui handles non-checksummed addresses

- packages/lib-sourcify/src/lib/solidityCompiler.ts
- src/server/controllers/VerificationController.ts
- test/server.js
- test/testcontracts/Storage/StorageJsonInput.json
- ui/src/components/ChainSelect/index.tsx
- ui/src/components/GitHubBranchSelect/index.tsx
- ui/src/components/Toast/index.tsx
- ui/src/components/fuzzySearch.tsx
- ui/src/constants.ts
- ui/src/pages/Verifier/CheckedContractsView/CheckedContract/ChainAddressForm/index.tsx
- ui/src/pages/Verifier/ContractInput.tsx
- ui/src/pages/Verifier/EtherscanInput.tsx
- ui/src/pages/Verifier/FileUpload.tsx
- ui/src/pages/Verifier/GitHubInput.tsx
- ui/src/pages/Verifier/SolcJsonInput.tsx
- ui/src/pages/Verifier/index.tsx
Closes #945 
- Adds session and non session endpoints
- Adds tests
- Adds solc json verification to the UI:
- Remove `CustomSelectSearch` and instead use the `SelectSearch` from the library itself with the correct types. CustomSelectSearch was there for a type workaround of the `onChange` prop: first removes the type, then adds the custom type. With the correct type from the library itself, there's no need for that.
- Refactor `fuzzySearch` to its own module as it's reused. 
- Refactor `ChainSelect` `GithubBranchSelect` 
- Add the new `SolcJsonInput.tsx` with the out-of-the-box `SelectSearch`.
> Verification with Standard JSON Input

- packages/lib-sourcify/src/lib/verification.ts
I was looking at some other contracts and noticed that for abstract contracts the compiler returns empty bytecode.
I believe we should immediately throw if the user is trying to verify an abstract contract or for some reason, the compiler returns an empty bytecode.
> Throw before if compiled bytecode empty instead of later in creation bytecode

- packages/lib-sourcify/README.md
- packages/lib-sourcify/src/index.ts
- packages/lib-sourcify/src/lib/CheckedContract.ts
- packages/lib-sourcify/src/lib/logger.ts
- packages/lib-sourcify/src/lib/solidityCompiler.ts
- packages/lib-sourcify/src/lib/verification.ts
- src/server/server.ts
* Created the simplest logging library inside LibSourcify (with no deps)
* change the default log level with `setLibSourcifyLoggerLevel`
* override the whole logging function with `setLibSourcifyLogger` implementing `ILibSourcifyLogger`
use the logger inside lib sourcify with `logError`, `logWarn`, `logInfo`, `logDebug`
@kuzdogan we need to decide what to log inside lib-sourcify
> Implement logging for LibSourcify

- src/sourcify-chains.ts
- test/chains/chain-tests.js
> Add Kava Mainnet Chain (2222)

- src/sourcify-chains.ts
- test/chains/chain-tests.js
- [x ] The branch is named as `add-chain-<chainId>`.
> add chain 314, Filecoin mainnet

- packages/lib-sourcify/src/lib/CheckedContract.ts
This helps when verifying contracts that don't have the CBOR metadata block at the end; currently, an error is thrown rather than making it a partial match.
> Catch auxdata decode error when checking for perfect match

- .vscode/launch.json
- environments/server.debug.linux-amd64.yaml
- packages/lib-sourcify/src/lib/solidityCompiler.ts
- src/Dockerfile.server.debug
Runs the process async without blocking the event loop.
Expected to improve the current high server response times.
Also adds Docker container to debug the linux-amd64 binaries (our server default) on host machines with different platforms.
> Async compiler process

- src/sourcify-chains.ts
- test/chains/chain-tests.js
- test/chains/sources/multicall3/Multicall3.sol
- test/chains/sources/multicall3/multicall3.metadata.json
> Add chain 13337

- services/ipfs/server/publish.sh
Example: 
`find: /data/contracts/partial_match/641230/: No such file or directory`
> stats gen: fix for when a partial_match dir doesn't exist for a chain id

- services/server/src/openapi.yaml
- services/server/src/servers.yaml
This PR refactors the OpenAPI docs to separate the endpoints from the `servers` list. It moves the `servers` list into a separate file.
When deploying the server image, the `servers.yaml` can be overridden to provide a custom `servers` list.
Fixes #1345.
> Move `servers` dropdown list into its own file

- serverless/compiler-lambda/index.js
- services/server/src/config/master.js
- services/server/src/config/staging.js
- services/server/src/server/controllers/verification/verification.common.ts
- services/server/src/server/services/compiler/lambda-with-fallback/SolcLambdaWithLocalFallback.ts
- services/server/src/server/services/compiler/lambda/SolcLambda.ts
See #1326
I didn't implement any chunking myself. Instead I used the `pipeline` function because the docs recommend to do so. AWS's `responseStream` will just take care of chunking it.
Note that that streamed responses also have a limit of 20 MB (usual payload response was 6 MB). Maybe it could make sense to fallback to local compilation if an error is received from the lambda function?
TODO:
> Stream lambda function compiler responses

- services/server/src/server/controllers/verification/session-state/input-files.session-state.paths.yaml
- services/server/src/server/controllers/verification/session-state/session-state.handlers.ts
- services/server/src/server/controllers/verification/verification.common.ts
- services/server/src/server/controllers/verification/verify/session/verify.session.handlers.ts
- services/server/src/server/controllers/verification/verify/session/verify.session.paths.yaml
- services/server/test/server.js
This PR adds a new query parameters to enable verification preview.
Fixes #1319.
> Add `dryrun` query param to enable verification preview

- services/server/src/server/controllers/repository/get-contract-addresses-paginated-full.stateless.paths.yaml
- services/server/src/server/controllers/repository/get-contract-addresses-paginated-partial.stateless.paths.yaml
- services/server/src/server/controllers/repository/repository.handlers.ts
- services/server/src/server/controllers/repository/repository.routes.ts
- services/server/src/server/services/StorageService.ts
- services/server/src/server/services/storageServices/SourcifyDatabaseService.ts
- services/server/src/server/services/utils/database-util.ts
- services/server/src/server/types.ts
- services/server/test/helpers/LocalChainFixture.ts
- services/server/test/helpers/ServerFixture.ts
- services/server/test/helpers/helpers.ts
- services/server/test/integration/repository-handlers/files.spec.ts
- services/server/test/integration/verification-handlers/verify.session.spec.ts
- services/server/test/integration/verification-handlers/verify.stateless.spec.ts
This PR was intended to add the `/files/contracts/partial/{chain}` endpoint that is missing to list all contracts under a certain chain.
However during the process, specifically when adding proper tests, I've noticed the `partial` and `any` endpoints not working as expected, and some other potential issues explained below for further investigation. 
TLDR;
- Adding the `/files/contracts/partial/{chain}` endpoint as specified in #1415 with an option to sort `asc` and `desc`
- Adding tests
- [SQL NULL comparison bug](#sql-null-comparison-bug)
- Potential issues:
- [Deduplication not working in `compiled_contracts`](#deduplication-not-working-in-compiled_contracts)
- [`matchType` not used in `database-utils.ts`](#matchtype-not-used-in-database-utils-ts)
This was due to the queries being used …
> Add `/files/contracts/partial/{chain}` endpoint and explicit ordering, resolve SQL NULL comparison bug

- services/server/src/server/controllers/verification/verification.common.ts
This PR fixes an issue when verifying multi-contract files with the `dryrun` flag enabled. The `dryrun` flag has been introduced in this PR https://github.com/ethereum/sourcify/pull/1343. When the logs were introduced in https://github.com/ethereum/sourcify/pull/1343/commits/8e78090d2416b3b80cd3a9e8cc34510717d92345, it changed the semantics. This PR fixes that.
Deploy the `SupraOracle` contract from this Hardhat project output [1cd581d3e27dff8cf701d43118fc3bdc.json](https://github.com/ethereum/sourcify/files/15393073/1cd581d3e27dff8cf701d43118fc3bdc.json).
Use the above output artifact in the `input-files?dryrun=true` endpoint.
Then the `verify-checked?dryrun=true` endpoint returns the contracts with `status: "error"`, but the `SupraOracle` should have `status: "perfect"`.
> Fix multi-contract verification when `dryrun` flag is enabled

- services/database/migrations/20231109160023-sourcify.js
- services/server/src/server/services/utils/database-util.ts
Fixes #1420 
I already ran the commands on the staging v2 database.
Additionally, I added all missing down functions in the migration of the sourcify database.
> db migration: Make `NULLS NOT DISTINCT` in `compiled_contracts_pseudo_pkey` constraint

- renovate.json
The current renovate PR fails, because the newest nock version causes problems. This disables updates for nock until we could fix it.
> Renovate: require dependencyDashboardApproval for nock

- packages/lib-sourcify/src/lib/types.ts
- services/server/src/server/services/utils/contract-creation-util.ts
- services/server/src/sourcify-chains-default.json
- services/server/test/unit/utils/contract-creation-util.spec.ts
Oasis chains, namely Sapphire and Emerald are migrating from blockscout to a new explorer backend called Nexus. This adds support for Nexus's API URLs and switches the chain definition to use that.
Oasis Sapphire and Oasis Emerald are "runtimes" (sometimes referred to as ParaTimes in marketing materials) on the Oasis network, so the runtime name is specified as part of the API configuration.
The Oasis Protocol Foundation runs official installations of Nexus at https://nexus.oasis.io (mainnet) and https://testnet.nexus.oasis.io (testnet).
> Oasis chains: add Nexus API fetcher

- services/server/src/config/master.js
- services/server/src/config/staging.js
Turning off writing to DBs to be able to do a release because the DB schema on prod. is not updated and the release would fail to write contracts. The repo writing logic must be unaffected by the latest changes. We are doing an earlier release to add new chains. The contracts after this change will get written to repoV1/2 and we will add them later during the migration.
And using repoV1 as the read source since writing to the DB is turned off.
Similarly the VerA DB schemas are still not ready. It is ok to have writing to VerA turned off on staging but it would be nice if we could get the VerA schema ready before the prod. migration so that we write everything simulatanously to Sourcify and VerA and don't have to move rows from Sourcify DB to VerA
> Turn off DBs

- package-lock.json
- services/monitor/package.json
- services/monitor/src/PendingContract.ts
The error detail inside "Error sending contract" errors in monitor is just 
```
{
message: "fetch failed"
name: "TypeError"
stack: "TypeError: fetch failed
at node:internal/deps/undici/undici:13178:13
at async PendingContract.sendToSourcifyServer (/home/app/services/monitor/dist/PendingContract.js:99:30)
at async /home/app/services/monitor/dist/ChainMonitor.js:178:25"
}
```
with no additional details. Reading online I found out that is probably a problem with the standard `fetch` API.
> Replace fetch with axios in monitor

- .dockerignore
When building the containers locally, nx and lerna will encounter a mismatch in device ids because the .nx folder containing the build cache is copied in the building container.
Ignore .nx to do a clean lerna build when building the Docker images locally
> Add .nx to dockerignore

- services/server/src/config/staging.js
On GCP, repositories and solc repos are not mounted under `/home/app/` but under `/home/app/data/`
> Update repositories and solc repos paths in staging config

- services/database/scripts.mjs
- services/server/src/config/default.js
- services/server/src/config/migration.js
- services/server/src/server/controllers/verification/verify/stateless/verify.stateless.handlers.ts
- services/server/src/server/controllers/verification/verify/stateless/verify.stateless.paths.yaml
- services/server/src/server/controllers/verification/verify/stateless/verify.stateless.routes.ts
Introduces changes to the DB sync script:
- Adds a `--deprecated` option to mark some chains deprecated and to send them to the `/verify-deprecated` endpoint instead.
- For more max concurrency, Removes the 1s wait between calls and reduces the `await` time inside the while loop
- Refactors `processContract` to remove the ineffective Promise. Prev. it was an `async` function returning a Promise, so it was a double Promise. Async functions should not return Promises.
- Conditionally enable `/verify-deprecated` in config
- Don't only send files with `.sol` and the `metadata.json` but all files. This is needed as some contract files don't have a file extension in our legacy repository.
> Changes to the database sync script

- services/server/src/config/master.js
- services/server/src/config/staging.js
Since we have rate limiting on our reverse proxy now by default, and now the deployment should be able to handle more requests, we can disable the rate limiting IMO
> Disable rate limiting on the application level

- services/server/src/server/services/storageServices/RepositoryV1Service.ts
- services/server/src/server/services/storageServices/RepositoryV2Service.ts
I think it's best if only the `stats-gen` job updates `manifest.json`, so that we know the exact timestamp of `stats.json`.
Let's remove `manifest.json` updates in `sourcify-server`.
https://github.com/ethereum/sourcify/blob/e3ae40c3a57989554d4cd3f75132bbc507185446/services/server/src/server/services/storageServices/RepositoryV1Service.ts#L485-L492
https://github.com/ethereum/sourcify/blob/e3ae40c3a57989554d4cd3f75132bbc507185446/services/server/src/server/services/storageServices/RepositoryV2Service.ts#L212-L219
> Do not update manifest.json for every new match stored

- services/monitor/README.md
- services/monitor/src/ChainMonitor.ts
- services/monitor/src/defaultConfig.js
- services/monitor/src/types.ts
- services/monitor/test/Monitor.spec.ts
Some of the /verify requests in the monitor running on GCP are failing with ECONNRESET error. We already tried debugging the problem but with no luck. Until we find a better solution we need to implement a retry mechanism in Monitor.
This PR implements a retry mechanism in Monitor configurable with: 
```
sourcifyRequestOptions: {
// Maximum number of retry attempts for contract verification requests after encountering an error
maxRetries: 3,
// Delay in milliseconds between each retry attempt for verification requests to Sourcify
retryDelay: 30000,
},
```
> Add sourcify request retry mechanism in Monitor

- services/server/src/common/async-context.ts
- services/server/src/common/logger.ts
- services/server/src/server/server.ts
GCP apparently advises usign the W3C standard `traceparent` header instead of the legacy `x-cloud-trace` header for traces: https://cloud.google.com/trace/docs/trace-context#legacy-http-header
These changes uses `traceparent` instead.
Additionally we extract the `traceId` portion of the whole header, instead of writing the whole identifier that includes other stuff. If we are in a GCP context, we now log these `traceId`s under `logging.googleapis.com/trace` as advised [here](https://cloud.google.com/run/docs/logging#correlate-logs) to enable automatic correlation in GCP.
> Use traceparent instead of x-cloud-trace-context, replace `requestId` with `traceId` everywhere

- services/server/.env.dev
- services/server/src/common/logger.ts
Solves `undefined` project id in log trace fields
> Add fallback and .env entry for project-id for log tracing

- services/server/src/openapi.yaml
Right now it doesn't make sense to have it between `/files` endpoints
> Move /repository endpoint upwards in the API doc

- scripts/check-s3-backup.mjs
See #1574 
Since we’ve discontinued using the Amazon S3 bucket as a backup, we should update `scripts/check-s3-backup.mjs` to point it to the Filebase S3 bucket.
> Point `check-s3-backup` test to Filebase S3

- packages/lib-sourcify/src/lib/validation.ts
- services/server/test/chains/chain-tests.spec.ts
Found in the [failin CI chain test (6119)](https://app.circleci.com/pipelines/github/ethereum/sourcify/6708/workflows/691eabb9-fba5-4a94-a762-a9344bc32471/jobs/40656), where it was unexpectedly fetching files from IPFS when the files are already provided.
Turns out when there are files with the same name, the files get overwritten by the `readFilesRecursively` function. Fixed by using a relative path as the key in the `files` object.
Also adds a log line to debug easier missing files when checking contracts
> Fix filename collusion

- packages/lib-sourcify/src/lib/CheckedContract.ts
- packages/lib-sourcify/src/lib/SourcifyChain.ts
- packages/lib-sourcify/src/lib/verification.ts
This PR adds two changes:
1. https://github.com/ethereum/sourcify/commit/2bf7168edc30416d38b5576552902141c9015373 fixes the incorrect return when a different auxdata was found in the creation bytecode. This became apparent when debugging the "cannot generate artifacts" error in #1562. Here the contract has a different auxdata at the end of the creation code because it returns raw bytecode of the factory contract. The verification logic incorrectly stops when it finds different auxdata, whereas it should've continued to find the auxdatas by editing the contract and recompiling.
2. Fixes the wrong match check (`match.creationBytecode` instead of `match.runtimeBytecode`) in the verification logic.
Also adds small modifications to logs during fetching traces for clarity.
> Fix verification logic

- services/server/src/server/controllers/verification/etherscan/etherscan.common.ts
Turns out the rate limit message has been changed. Modifies the condition to detect rate limits
> Fix Etherscan 429 condition

- services/monitor/src/Monitor.ts
- services/monitor/src/types.ts
- services/monitor/test/Monitor.spec.ts
I've noticed I forgot to push the commits to https://github.com/ethereum/sourcify/pull/1616 and merged without the tests.
Here are the tests for added coverage, written with AI
> Add tests for Monitor authenticateRpcs

- services/server/src/server/server.ts
- services/server/src/server/services/storageServices/AbstractDatabaseService.ts
- services/server/src/server/services/storageServices/SourcifyDatabaseService.ts
- services/server/src/server/services/utils/database-util.ts
- services/server/src/server/session.ts
With the new Verifier Alliance database schema naming system, the schemas are named `v0`, `v1`,...  We should add support to custom schemas in AbstractDatabaseService.
This PR adds the support to custom schemas also to the database session
Open questions: 
- Manually adding `"schema"."table"` before every table is the only way I found to implement this. I'm open to suggestions
> Support custom schema in AbstractDatabaseService and database session

- services/database/migrations/20240924163455-make-compiled_contracts-creation-not-null.js
From kaan
> Do these changes make sense? https://github.com/ethereum/sourcify/blob/6156037dde2374260830fd832b6f9831d16bf1fe/services/database/migrations/20231109160023-sourcify.js#L33-L39
> I checked and there are no contracts with null compiled_contracts.creation_code_hash and _artifacts
Indeed those fields can be set as non nullable fields.
This PR sets `creation_code_hash` and `creation_artifacts` as NOT NULL.
I already executed this script on both production and staging.
> Make `compiled_contracts.creation_code_hash` not nullable

- scripts/rename_repov2_sol_extension.sh
Adding the script to remove the .sol extension from contracts in repoV2. I will run it now after merging https://github.com/ethereum/sourcify/pull/1648 on staging. On production, I will run it once we do a new release.
> Add rename_repov2_sol_extension.sh script

- package-lock.json
- services/database/.env.template
- services/database/package.json
- services/database/schema-updates/post-v0-to-v1-upgrade.mjs
After running the script in #1635, `sources.source_hash_keccak` is empty. Since Postgresql doesn't support keccak256, we need to manually update the column. In this PR, a script is implemented to update each `sources.source_hash_keccak`
> Add script to finalize v1 migration

- services/server/src/server/services/storageServices/AbstractDatabaseService.ts
- services/server/test/helpers/helpers.ts
- services/server/test/integration/verification-handlers/verify.stateless.spec.ts
Inside the function `AbstractDatabaseService.updateExistingVerifiedContract` we didn't call https://github.com/ethereum/sourcify/blob/c14282cbac1e6d5e407e309c7d7dcf935b78adc6/services/server/src/server/services/storageServices/AbstractDatabaseService.ts#L444-L449
So all match upgrades were not containing sources.
> Fix missing source after match upgrade

- scripts/release/git_utils.sh
- scripts/release/main.sh
Updates the release script to not merge master back to staging after release, as discussed in https://github.com/ethereum/sourcify/pull/1638
Previously we did:
- Open a PR from staging to master
- merge staging to master locally
- choose package versions, write and commit changelogs (on master)
- choose the versions in lerna
- push the tags to the origin
- push the commits to origin/master, this will merge the PR
- create GH releases
- Merge master back to staging (this now requires another PR)
The changes do the following:
- Open a PR from staging to master
- Locally go to staging
- Create a new branch from staging called `commit-changelogs-2024-01-01`
- Choose package versions, write and commit changelogs
- Publish `commit-changelogs-2024-01-01`, and open a PR to staging.
- Approve and …
> Update the release script to avoid merging master back to staging

- .vscode/launch.json
- services/monitor/monitorChains.json
- services/monitor/src/ChainMonitor.ts
The Monitors were crashing because we were throwing here
https://github.com/ethereum/sourcify/blob/33cc02ec655596b8f1001ec52c2b0c4ab987f91a/services/monitor/src/ChainMonitor.ts#L348-L351
- Removes the throw
- Fixes the Avalanche RPC URLs
- Removes the launch.json built and run Monitor
> Fixing Monitor crashing regularly, small additional fixes

- services/server/src/sourcify-chains-default.json
- services/server/test/chains/chain-tests.spec.ts
I have added an `rpc` field to Zircuit Testnet because [chains.json](../../src/chains.json) has an obsolete address that uses http instead of https. [chainid.network](https://chainid.network/chains.json) needs to be updated.
> Add chain 48900 48899

- services/server/test/helpers/etherscanInstanceContracts.json
This test is failing in the CI.
> Etherscan instance tests for 2442: change expected status of 0xd5a515CE2dF4C69aA809De5b9318a3D4452D86BE to partial

- .circleci/scripts/publish_to_npm.sh
The changes adds the sourcify-server package to be published to npm.
It also adds a check to only publish the packages in their own tagged CI runs. Previously e.g.  when there was a new tag for theese packages, both lib-sourcify and bytecode-utils's CI runs tried to publish both packages. This results in the first one succeeding and publishing both packages but the second one to fail.
Now we check to only publish the package in their corresponding tag CI builds.
Related to #1661. Still need to add the docs how to use the server package.
Edit: TBH I'd skip adding the docs because it's rather complicated to set up a `new Server()` with options. I tried to do the fixes and it takes a lot of time. I'd postpone it until someone requests it and also until #1665
> Publish sourcify-server and only publish the package in its own CI run

- .circleci/nightly.yml
This PR disables `s3-backup-check`. Let's keep this disabled until we implement a fix for the s3 sync script.
> Disable `s3-backup-check`

- .circleci/scripts/publish_to_npm.sh
Publishing the `sourcify-server` on npm failed on CI because of the wrong package name: https://app.circleci.com/pipelines/github/ethereum/sourcify/7227/workflows/fc503e37-673d-42a6-b69e-c318145e95b3/jobs/43733
Fixes this by giving the correct package name
> Fix wrong tag name for sourcify-server in the npm publish script

- services/server/src/sourcify-chains.ts
Fixes #1734 
After merging https://github.com/ethereum/sourcify/pull/1732, we were skipping RPCs in the CI, when no environment variables are available. This led to no rpcs being available for some chains. 
With this PR, we first try the rpcs in sourcify-chains.json, and if all were skipped we make use of the ones in chains.json.
> Fix no RPCs available in CI

- services/server/src/server/services/storageServices/RepositoryV2Service.ts
Currently when we successfully store a contract on s3, we get a log: `Stored contract to RepositoryV2`. This PR fixes this problem.
> Fix logging for S3RepositoryService

- packages/lib-sourcify/test/compiler/vyperCompiler.ts
- services/server/src/server/services/compiler/local/vyperCompiler.ts
I investigated which architectures the binaries are built for. I only had to add a check for Mac binary. I also improved the logging a bit because it was confusing when I tried to run a vyper verification.
> Improve platform architecture management for Vyper compiler

- packages/lib-sourcify/src/lib/AbstractCheckedContract.ts
- packages/lib-sourcify/src/lib/SolidityCheckedContract.ts
- packages/lib-sourcify/src/lib/VyperCheckedContract.ts
- packages/lib-sourcify/src/lib/types.ts
- packages/lib-sourcify/src/lib/verification.ts
- packages/lib-sourcify/test/sources/Vyper/withImmutables/artifact.json
- packages/lib-sourcify/test/sources/Vyper/withImmutables/test.vy
- packages/lib-sourcify/test/verification.spec.ts
- services/server/src/server/controllers/verification/verify/stateless/verify.stateless.handlers.ts
This PR adds support to Vyper immutables. Now Sourcify can handle immutables transformations for Vyper and partial matches with contracts with immutables.
We use the information in the cbor auxdata: `['runtime_size', 'data_sizes', 'immutable_size', 'compiler']`, in particular we use `immutable_size` to extract the immutables from the end of the onchain runtime bytecode.
> Add support for immutables in Vyper

- packages/lib-sourcify/src/lib/VyperCheckedContract.ts
- packages/lib-sourcify/test/functions.spec.ts
This would blow up the metadata.json for Vyper contracts significantly. The source should be accessed through the source file, not the metadata.
> Don't store full source content in mocked Vyper metadata object

- packages/lib-sourcify/src/lib/SourcifyChain.ts
- services/server/src/server/services/utils/contract-creation-util.ts
- services/server/test/helpers/LocalChainFixture.ts
- services/server/test/helpers/helpers.ts
- services/server/test/integration/repository-handlers/files.spec.ts
- services/server/test/integration/verification-handlers/verify.stateless.spec.ts
- services/server/test/unit/utils/contract-creation-util.spec.ts
Adds a new function `findContractCreationTxByBinarySearch` to do a lower bound binary search for the transaction that created the contract.
Calls `eth_getCode` on the middle blocks to see if the contract has code. If yes, the contract should be created before this block. If no code, the contract should be created after this block.
Once the block is found, searches through all the tx's of the block to see if any of them created this contract.
Only supports EOA contract creations (tx.to === null). Tracing every single tx would've been quite expensive.
Adds unit tests and an integration test for the Mainnet Tether contract to test the function.
> Add binary search for creator tx hash

- services/server/src/server/services/utils/contract-creation-util.ts
- services/server/test/unit/utils/contract-creation-util.spec.ts
This fixes the creation tx hash fetching from the Blockscout API after the unexpected change of `creation_tx_hash` to `creation_transaction_hash`.
Also block binary search during the tests to correctly test the specific case
> Fix creation tx fetching from blockscout after the API change

- services/server/src/config/master.js
I already added the environment variables on GCP. The only thing left is to add `WStorageIdentifiers.S3Repository` in the production configurations.
> Activate S3Repository in production

- services/server/src/apiv2.yaml
- services/server/src/openapi.yaml
- services/server/src/server/apiv1/repository/check-all-by-addresses.stateless.paths.yaml
- services/server/src/server/apiv1/repository/check-by-addresses.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-contract-addresses-all.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-contract-addresses-paginated-all.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-contract-addresses-paginated-full.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-contract-addresses-paginated-partial.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-file-static.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-file-tree-all.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-file-tree-full.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-source-files-all.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-source-files-full.stateless.paths.yaml
- services/server/src/server/apiv1/verification/etherscan/session/etherscan.session.paths.yaml
- services/server/src/server/apiv1/verification/etherscan/stateless/etherscan.stateless.paths.yaml
- services/server/src/server/apiv1/verification/session-state/clear.session-state.paths.yaml
- services/server/src/server/apiv1/verification/session-state/data.session-state.paths.yaml
- services/server/src/server/apiv1/verification/session-state/input-contract.session-state.paths.yaml
- services/server/src/server/apiv1/verification/session-state/input-files.session-state.paths.yaml
- services/server/src/server/apiv1/verification/solc-json/session/solc-json.session.paths.yaml
- services/server/src/server/apiv1/verification/solc-json/stateless/solc-json.stateless.paths.yaml
- services/server/src/server/apiv1/verification/verify/session/verify.session.paths.yaml
- services/server/src/server/apiv1/verification/verify/stateless/verify.stateless.paths.yaml
- services/server/src/server/apiv1/verification/vyper/stateless/vyper.stateless.paths.yaml
- services/server/src/server/server.ts
`apiv2.yaml` is directly retrieved from Stoplight and can just be copy-pasted again when an update is needed in the future. Only if we add more endpoints we need to manually reference them in `openapi.yaml` due to limitations of the OpenAPI spec.
Needed to change the mode of the validator's refparser because the we reference the same file multiple times now.
~~I'm not sure about the tags for the swagger documentation yet. Maybe we should add a "deprecated" to APIv1 instead of the "API v1" prefix?~~
> Add APIv2 OpenAPI specification

- services/server/src/sourcify-chains-default.json
See #1835 
Etherscan seems to have changed something about their instances. Some instances seem to not have required an API key, and for some of these we didn't set up a key in the CI or didn't configure them properly in the `sourcify-chains-default.json`.
This PR fixes the latter. I already added the missing env variables to the CI.
> Add missing Etherscan api key env names

- packages/lib-sourcify/src/lib/verification.ts
- packages/lib-sourcify/test/verification.spec.ts
Fixes #1835
Fixes a bug #1839 introduced.
In case `cborAuxdataPositions = {}`, `Object.values(cborAuxdataPositions).every(...)` evaluates to true and therefore matches the creation match to perfect.
> Fix matching creation bytecode when no cborAuxdataPositions could be generated

- packages/lib-sourcify/src/Compilation/SolidityCompilation.ts
- packages/lib-sourcify/src/Compilation/VyperCompilation.ts
- packages/lib-sourcify/test/Compilation/SolidityCompilation.spec.ts
- packages/lib-sourcify/test/Compilation/VyperCompilation.spec.ts
- packages/lib-sourcify/test/sources/NoImmutableField/metadata.json
- packages/lib-sourcify/test/sources/NoImmutableField/sources/NoImmutable.sol
> Implement Compilation tests with 100% coverage

- services/server/src/apiv2.yaml
- services/server/src/server/apiv2/middlewares.ts
- services/server/test/integration/apiv2/lookup.spec.ts
Closes #1887 
I added `allowReserved` to fields and omit parameters in Stoplight to prevent users from having to encode the `,` and `*` characters.
> Add `/v2/contract/{chainId}/{address}?fields=*` option

- services/server/test/chains/chain-tests.spec.ts
#1888 introduced a formatting error, which is why the CI fails on staging.
> Fix formatting

- packages/lib-sourcify/src/lib/SourcifyChain.ts
While debugging why holesky monitor for `0xC13971850152480FE12238676066A9a9D6d0296a` failed, I could see the bytecode was fetched but couldn't see if the RPC returned an empty or invalid response and there were no other informative logs. 
By logging the bytecode length and first bytes we can see what happened there. 
This should be reflected in #1879 @marcocastignoli
> Log the fetched bytecode length and first 32 bytes

- services/server/src/sourcify-chains-default.json
- services/server/test/chains/chain-tests.spec.ts
This pull request includes updates to the `services/server` to support the XDC Network and update the XDC Apothem Testnet. The changes primarily involve adding support for the XDC Network and updating the testnet configuration and tests.
Support for XDC Network:
* [`services/server/src/sourcify-chains-default.json`](diffhunk://#diff-ca61b58909fd176243490a3dd9ed979b5b47ae6631fbebba3307f1678d1e131dR154-R168): Added support for the XDC Network with the chain ID `50`, including the `blocksScanApi` URL for contract creation transaction fetching.
Updates to XDC Apothem Testnet:
* [`services/server/src/sourcify-chains-default.json`](diffhunk://#diff-ca61b58909fd176243490a3dd9ed979b5b47ae6631fbebba3307f1678d1e131dR154-R168): Updated the `sourcifyName` and `blocksScanApi` URL for the XDC Apothem …
> Added chain 50: XDC Network Mainnet

- .circleci/new_branch.yml
- .circleci/test-chains-regularly.yml
- package.json
the chain tests were run twice in the CI because we had an unnecessary command in the monorepo package.json. 
This should also fix the git submodule error we saw.
> Simplify chain tests commands

- services/server/src/server/apiv2/lookup/lookup.handlers.ts
- services/server/src/server/services/storageServices/SourcifyDatabaseService.ts
- services/server/src/server/services/utils/Database.ts
- services/server/test/integration/apiv2/lookup.spec.ts
Fixes #1918 
The SQL query used a usual join on the creation bytecode which makes it not possible to retrieve a contract in case we didn't store the creation code.
The other issue was that the proxy resolution was run even though a contract is not veried.
> Fixes to GET `/v2/contract/`

- services/server/src/server/services/utils/database-util.ts
- services/server/test/integration/apiv2/lookup.spec.ts
Fixes #1941 
The `concat('0x', ...)` function simply returns `0x` in case the second argument is NULL. This caused the problem from the linked issue.
> Ensure to return NULL for any NULL value on the GET contract endpoint

- packages/lib-sourcify/src/lib/SourcifyChain.ts
- services/server/src/sourcify-chains.ts
Fixes #1891 
Also removes the useless warning message about Websockets.
> Do not throw when chain API keys missing on production

- services/server/src/sourcify-chains.ts
Do not continue in the loop to allow overriding the test chains below with the user provided sourcify-chains.json content.
> If user provides 1337, and 31337 test chains, use the user config instead of default LOCAL_CHAINS config

- services/server/README.md
This adds a short subsection to the server docs explaining how to connect Sourcify to an RPC server running on the Docker host. I had to spend some time searching online for this before I was able to get Sourcify to connect to a development node on my machine, so maybe this information would be useful for others, too.
> Add information about connecting to an RPC on the Docker host

- packages/lib-sourcify/src/Compilation/CompilationTypes.ts
- packages/lib-sourcify/src/Compilation/SolidityTypes.ts
- packages/lib-sourcify/src/Compilation/VyperTypes.ts
- packages/lib-sourcify/src/Verification/Verification.ts
- packages/lib-sourcify/src/Verification/VerificationTypes.ts
Needed for API v2 verify endpoints (https://github.com/ethereum/sourcify/issues/1910). The export will be returned from the verification worker.
> Add VerificationExport

- services/server/src/openapi.yaml
- services/server/src/server/apiv1/repository/check-all-by-addresses.stateless.paths.yaml
- services/server/src/server/apiv1/repository/check-by-addresses.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-contract-addresses-all.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-contract-addresses-paginated-all.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-contract-addresses-paginated-full.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-contract-addresses-paginated-partial.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-file-static.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-file-tree-all.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-file-tree-full.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-source-files-all.stateless.paths.yaml
- services/server/src/server/apiv1/repository/get-source-files-full.stateless.paths.yaml
Updates the API docs in order to encourage users to use v2 lookup.
> Deprecate v1 repository endpoints in openapi spec

- services/server/src/sourcify-chains-default.json
- services/server/test/chains/chain-tests.spec.ts
Updates deprecated explorer URL for Happychain Testnet and updates test
> fix: update happy testnet (new url)

- services/server/src/common/errors/BadGatewayError.ts
- services/server/src/common/errors/BadRequestError.ts
- services/server/src/common/errors/ConflictError.ts
- services/server/src/common/errors/ContractIsAlreadyBeingVerifiedError.ts
- services/server/src/common/errors/GenericErrorHandler.ts
- services/server/src/common/errors/InternalServerError.ts
- services/server/src/common/errors/NotFoundError.ts
- services/server/src/common/errors/PayloadTooLargeError.ts
- services/server/src/common/errors/TooManyRequests.ts
- services/server/src/common/interfaces.ts
- services/server/src/server/apiv2/errors.ts
Rename `code` of `IResponseError` to `statusCode`
Needed to avoid interfering with postgres errors that also have a `code` property.
Adds logging for all unknown errors.
Also renames deprecated `getStatusText` method of HttpStatus to `getReasonPhrase`
> Improve express error handler

- services/server/src/server/apiv2/middlewares.ts
Came across this check which was simply wrong before.
It should not start a new verification if any of the jobs is not completed.
There is already a test for this check, not sure if it is worth to have another.
> Fix check for running jobs

- services/server/test/chains/chain-tests.spec.ts
The Auroria testnet was restarted and this contract had to be re-deployed.
See #1381 and #2056
> Update verifyContract for Auroria (chain 205205)

- services/server/src/sourcify-chains-default.json
- services/server/test/chains/chain-tests.spec.ts
…rted
* Mark Ethereum Mekong Testnet, WAGMI Testnet, Kanazawa Testnet, MELD, Tiltyard Subnet, Garnet Holesky, and PlayFair Testnet Subnet as unsupported.
* Remove associated fetchContractCreationTxUsing configurations for these chains.
* Update chain-tests.spec.ts to comment out tests for the unsupported chains.
> Remove support for chains

- services/server/src/chains.json
- services/server/src/sourcify-chains-default.json
This is only a URL update but seems related to contract verification issue (probably your backend is trying to reach the old explorer URL).
Thanks in advance for your kind help.
> Update URL of Syscoin Testnet Tanenbaum explorer (chain 5700).

- packages/lib-sourcify/README.md
- packages/lib-sourcify/src/SourcifyChain/SourcifyChain.ts
- packages/lib-sourcify/src/SourcifyChain/SourcifyChainTypes.ts
- packages/lib-sourcify/src/Validation/SolidityMetadataContract.ts
- packages/lib-sourcify/src/Validation/fetchUtils.ts
- packages/lib-sourcify/src/index.ts
- packages/lib-sourcify/src/logger.ts
- packages/lib-sourcify/test/Validation/fetchUtils.spec.ts
- services/monitor/src/Monitor.ts
- services/monitor/test/Monitor.spec.ts
- services/server/src/common/logger.ts
- services/server/src/server/apiv1/verification/session-state/session-state.handlers.ts
- services/server/src/server/cli.ts
- services/server/src/server/server.ts
- services/server/src/sourcify-chains.ts
- services/server/test/helpers/LocalChainFixture.ts
In this PR I'm removing environment variables from `lib-sourcify`. 
- We already have `setLibSourcifyLoggerLevel` to change the log level of lib-sourcify
- I added `SourcifyChain.setGlobalRpcTimeout` to change the rpc timeout in `SourcifyChain`
- I added `SolidityMetadataContract.setGlobalIpfsGateway` to change the `IpfsGateway`. I decided to not create a custom function outside of `SolidityMetadataContract` because that's the only place in which we use the `IpfsGateway`
- The `LibSourcify.SourcifyChainsExtensionsObject` doesn't have anymore a `headerEnvName` parameter. Now it has only a `headerValue` parameters. Consequently I had to create a custom `SourcifyServer.SourcifyChainsExtensionsObjectWithHeaderEnvName`, that includes `headerEnvName`, and at server's boot it loads the …
> Remove environment variables  from lib-sourcify

- services/server/test/helpers/etherscanInstanceContracts.json
This PR fixes the failing `etherscan-instances` CI test
> Add etherscan instance test for Hoodi

- .circleci/continue_config.yml
- .circleci/new_branch.yml
9db1250d2b1126a4f6b645b9681cb54b1c68bdc9 removed the coloring of the package in the CI logs. It seems like we need to call `npx lerna` directly to have the output colored.
> Fix coloring in CI logs

- services/server/src/sourcify-chains.ts
Currently, when you use custom `sourcify-chains.json` there is a problem for networks that are not present `chains.json`, it is then categorized as `unknownChain` and not all of the properties are being copied when populating `sourcifyChainsMap`.
I've added `fetchContractCreationTxUsing` to prevent contract creation transaction being fetched only through binary search wtih RPC.
> copy `fetchContractCreationTxUsing` for an unknown chain

- services/server/src/common/errors/GenericErrorHandler.ts
This addresses the problem that, in GCP, the error message is hidden in the payload properties
> Log error message for unexpected server errors

- services/server/src/openapi.yaml
- services/server/src/server/apiv1/repository/get-file-static.stateless.paths.yaml
> Update OpenAPI paths to use 'matchType' instead of 'full_match | partial_match' for repository contracts

- services/server/src/common/logger.ts
- services/server/src/server/cli.ts
- services/server/src/server/server.ts
- services/server/test/helpers/ServerFixture.ts
#2058 introduced two issues:
- The log level was set to warning in production mode (before it was info)
- The type of the `NODE_LOG_LEVEL` environment variable changed from string to number. I think we don't need this breaking change and it led to the issue before.
This PR fixes these issues and makes general improvements to the logging.
> Fix server logging

- package-lock.json
- services/server/package.json
- services/server/src/server/services/utils/etherscan-util.ts
- services/server/test/chains/etherscan-instances.spec.ts
- services/server/test/helpers/assertions.ts
- services/server/test/helpers/etherscanInstanceContracts.json
A couple of problems were introduced with the API v2 Etherscan import:
- Errors from the newly introduced Solidity parser were not caught. This could cause the server to crash.
- The Solidity parser had a bug in version 0.20.0 that made it not work with a few contracts that use `at` as an identifier.
- The etherscan instance tests needed some fixes
> Fix v2 Etherscan import and tests

- services/server/src/sourcify-chains-default.json
- services/server/test/chains/chain-tests.spec.ts
> Added new chains 42793 & 128123

- services/server/src/apiv2.yaml
- services/server/src/openapi.yaml
- services/server/src/servers.yaml
- Moved description etc. to the main openapi.yaml instead of v2 a3563b5b77c7b66c36eee6e2aa48b698648f78c5
- Converted "examples:" fields with one example to "example:" to show on swagger ui 51e54a0b527b8414e8d1297642c7c10d6dd77e84 SwaggerUI wasn't able to parse example arrays and show. Now we show examples values in path paramter {chainId} for example
> Cleanup openapi.yaml

- services/server/src/openapi.yaml
if you are on docs.sourcify.dev, the link just brings you to the same page.
> Update openapi.yaml to remove link to docs.sourcify.dev

- packages/compilers/.mocharc.json
- services/server/.mocharc.json
Fixes #2107
Regarding the flaky tests on the new verification endpoints: The issue seems to be that they are the first test in the describe block (server is started at the beginning of the describe block) and it takes some time to spin up the worker thread. The first tests per describe block run for around 1 minute because they need to wait for the thread to be ready. Therefore, they hit only sometimes the 1 minute timeout.
On the compilers package, we also have a test where the compilation takes over 1 minute sometimes. This wasn't a problem before we had the compilers package, because this test was inside the lib-sourcify tests and there we have not timeout configured.
This simply increases the Mocha timeouts to 2 minutes. Hopefully, this is enough.
> Fix flaky tests

- services/server/src/server/services/workers/verificationWorker.ts
Fixes #2074
Call internal `_verifyFromJsonInput` inside `_verifyFromEtherscan` instead of public function. Needed because the traceId was overwritten with undefined when calling the public function.
> Fix traceId not logged inside worker when verifying via Etherscan import

- packages/lib-sourcify/src/Verification/Verification.ts
- services/server/src/server/apiv1/verification/private/stateless/private.stateless.handlers.ts
See #2091
In the upgrade script the `compilation.metadata` object was not mocked. `extractConstructorArgumentsTransformation` needs the metadata.abi object in order to extract the constructor arguments from the onchain creation bytecode. Without the metadata the constructorArguments transformation coulnd't be found.
This PR adds the metadata field on the mock compilation
> Fix missing compilation.metadata field in upgrade script

- .gitignore
- scripts/release/main.sh
- scripts/release/release.sh
- scripts/release/release_data_utils.sh
Fixes to the release process following the last release call:
-  Use a temporary file for storing package version etc. in release scripts instead of memory variables
- use `--include-merge-tags` flag to correctly determine which packages are changes
- Fix GUI editors like `code` exiting before writing to temp changelog file.
I ran it to the extent that I can (without publishing a release etc.) and seems stable. We can check again on our next release if it goes well 🤞
> Release process fix 2

- services/server/README.md
- services/server/src/server/apiv2/routes.ts
- services/server/test/integration/apiv2/v2.common.spec.ts
Closes #1981
This does two things:
- Clarify in server README that a database is required for API v2
- Return a 404 on /v2 endpoints if no database is configured
I also checked if the example configuration in the README works. I had no problems with running it.
> Clarify that a Postgres database is required for API v2

- scripts/release/git_utils.sh
- scripts/release/main.sh
Previously, the final steps of the release process included merging staging into master. With this PR, we replace those steps by requiring the user to manually approve and merge the pull request directly on GitHub.
> In the release script don't merge staging to master

- codecov.yml
Closes #2073 
Easing the Codecov PR status checks a bit.
- allows project wide coverage to drop by max 0.5 % per PR
- requires to have at least 70 % coverage on the PR changes
> Change Codecov status checks

- packages/compilers-types/src/SolidityTypes.ts
- services/server/src/server/services/StorageService.ts
- services/server/src/server/services/storageServices/SourcifyDatabaseService.ts
- services/server/src/server/services/utils/Database.ts
- services/server/test/helpers/mocks.ts
- services/server/test/integration/storageServices/SourcifyDatabaseService.spec.ts
Closes https://github.com/ethereum/sourcify/issues/2167
This will make the verification job fail, if the server cannot store a new `verified_contract` due to a conflict with the constraints. The error code of the job will be an `internal_error` because, in future, this case should not be encountered regularly and generally points to a bug on our side. We only have it in https://github.com/ethereum/sourcify/issues/2092 because the contracts were verified with a buggy version of Sourcify before.
Also:
- Removes the storageService reference from SourcifyDatabaseService because it was not used
- Corrects the StorageLayout type which didn't match the actual values of this type
> Throw an error on conflict when inserting a verified_contract

- services/server/src/apiv2.yaml
- services/server/src/openapi.yaml
- services/server/src/server/apiv2/lookup/lookup.handlers.ts
- services/server/src/server/apiv2/lookup/lookup.routes.ts
- services/server/src/server/services/StorageService.ts
- services/server/src/server/services/storageServices/SourcifyDatabaseService.ts
- services/server/src/server/services/utils/Database.ts
- services/server/src/server/services/utils/database-util.ts
- services/server/test/helpers/LocalChainFixture.ts
- services/server/test/helpers/ServerFixture.ts
- services/server/test/helpers/helpers.ts
- services/server/test/integration/apiv2/lookup.spec.ts
- services/server/test/integration/apiv2/lookup/all-chains.spec.ts
- services/server/test/integration/apiv2/lookup/contract-details.spec.ts
- services/server/test/integration/apiv2/lookup/contracts-by-chain.spec.ts
Closes #2114 
Adding a new enpoint under `/v2/contract/allChains/:address`. Let me know if you have feedback regarding the endpoint naming choice.
The endpoint returns an array of VerifiedContractMinimal under the `results` field on the response body. If there are no contracts at this address on any chain, it returns `404` with an results array that is empty `[]`. Idk if this is good practice and we should return `200`?
- Bumps the APIv2 version to v2.1.0
- Implements the queries, handlers, and the endpoint.
- Add tests
I appreciate a detailed look on the DB query. 
Todo:
> V2 address lookup on all chains endpoint

- .circleci/config.yml
- .circleci/scripts/publish_to_npm.sh
Turns out we haven't been publishing sourcify-server since 8 months because of a `@ethereum-sourcify` prefix check in our CI :(
https://www.npmjs.com/package/sourcify-server
> Fix npm not publishing sourcify-server because of prefix check

- services/server/src/server/apiv1/verification/solc-json/stateless/solc-json.stateless.handlers.ts
- services/server/src/server/services/utils/etherscan-util.ts
- services/server/src/server/services/utils/parsing-util.ts
- services/server/test/unit/utils/etherscan-util.spec.ts
- services/server/test/unit/utils/parsing-util.spec.ts
See #2206 
The breaking request of #2206 fails on the unzip method as far as I can tell from the logs. The unzip is called with Metadata files that we get from recompiling the contract a first time. The first recompilation via the provided std json works. Since the processing via Metadata is a workaround from legacy code, we can remove this step and directly call the actual compilation for the std json, and verify from there. This should hopefully fix the server for this request, otherwise I added logging to check what the provided parameters and then we can debug further.
> Verify via SolidityCompilation directly inside /verify/solc-json endpoint

- services/server/src/apiv2.yaml
- services/server/src/server/services/utils/etherscan-util.ts
I found myself having to check the compiler version format and where we put the language field. So adding the examples in the API docs for reference.
Also logs the first letters of Etehrscan API keys to be able to understand which key is in use
> Add examples to the std-json input + log API key's first letters

- .circleci/continue_config.yml
- .circleci/new_branch.yml
Our CI wasn't running the linting step because we used the wrong name. See here for example: https://app.circleci.com/pipelines/github/ethereum/sourcify/9122/workflows/099a1479-1c58-4eb8-876e-e034aa94277d/jobs/53585/parallel-runs/0/steps/0-105
> fix: update lint command to use 'check' instead of 'lint' in CI configurations

- .circleci/nightly.yml
Fix for the nightly CI run:
https://app.circleci.com/pipelines/github/ethereum/sourcify/9129/workflows/ae6ef024-617d-4c1e-850a-8d668ca4ace6/jobs/53631
> fix: remove redundant migration command from etherscan instance nightly ci test

- package-lock.json
- packages/bytecode-utils/package.json
- packages/compilers/package.json
- packages/lib-sourcify/package.json
There were these warnings when you installed the packages:
```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@ethereum-sourcify/lib-sourcify@2.1.5',
npm warn EBADENGINE   required: { node: '22.5.1' },
npm warn EBADENGINE   current: { node: 'v22.17.1', npm: '10.9.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@ethereum-sourcify/bytecode-utils@1.3.9',
npm warn EBADENGINE   required: { node: '22.5.1' },
npm warn EBADENGINE   current: { node: 'v22.17.1', npm: '10.9.2' }
npm warn EBADENGINE }
```
> fix: update Node.js engine version to >=22.0.0 in package.json files

- services/server/src/sourcify-chains.ts
If an RPC is skipped because the API key is missing, this affects the `index` property of RPCs with traces. The RPC with trace ends up with a wrong index and when being used it becomes `undefined`.
The fix keeps track of the RPCs skipped and reduces that number from the index.
> Fix RPC index of others when an RPC is skipped

- services/database/.env.template
- services/database/massive-replace-script/README.md
- services/database/massive-replace-script/config-constructor-arguments-transformation.js
- services/database/massive-replace-script/massive-replace-script.ts
- services/server/src/server/apiv1/verification/private/stateless/customReplaceMethods.ts
- services/server/src/server/apiv1/verification/private/stateless/private.stateless.handlers.ts
See #2208
This adds a new configuration for the massive replace script to fix the contracts of the linked issue. We found one problem in the `replace-contract` endpoint that led to writing an empty transaction hash when replacing. This is also addressed by correctly assigning the transaction hash which is retrieved from the database. Additionally, this adds smaller adjustments to the massive replace script like an option to store info about contracts which failed replacing.
> Replace script config for fixing missing constructor args transformations

- services/database/.gitignore
- services/database/massive-replace-script/config-replace-metadata.js
- services/database/massive-replace-script/massive-replace-script.ts
- services/server/src/server/apiv1/verification/private/stateless/customReplaceMethods.ts
- services/server/src/server/apiv1/verification/private/stateless/private.stateless.handlers.ts
- services/server/src/server/apiv1/verification/private/stateless/private.stateless.paths.yaml
See #2227
- adds the configuration to the massive replace script for fixing the above issue
- adds an option to exclude contracts from submission to the `replace-contract` endpoint in order to only update contracts with wrong metadata
- adds a new custom replace method to only update metadata on the submitted contract
> Replace script config for fixing mismatched metadata

- services/monitor/Dockerfile
- services/server/Dockerfile
- services/server/Dockerfile.debug
- services/server/docker-compose.local.yml
- services/server/docker-compose.yml
Fixes #2258, #2229
Upgrades the server Docker base image from node:22.5.1-bullseye to node:22.5.1-bookworm to resolve glibc compatibility issues with Vyper compiler binaries.
Problem:
- Vyper compiler binaries (v0.4.3+) require glibc 2.35+ for proper execution
- Debian Bullseye ships with glibc 2.31, causing runtime errors when downloading and executing Vyper binaries programmatically
- Error: GLIBC_2.35' not found prevents Vyper compilation functionality
Solution:
- Debian Bookworm provides a newer version of glibc, meeting Vyper's requirements
- Updates both builder and production stages to use bookworm-based images
- Maintains compatibility with existing Node.js 22.5.1 runtime
> Update Dockerfiles from Bullseye to Bookworm for Vyper compiler compatibility

- .circleci/config.yml
- .circleci/continue_config.yml
- .circleci/new_branch.yml
This morning we created a new CircleCI organization using a different auth method than OAUTH. This caused several problems:
- there is no `pipeline.git.base_version` support
- the organization slug is `circleci/2bWbncbTSPHJDSWS2B9PoE` instead of `argotorg`, causing the codecov CircleCI orb to fail
- **Most importantly**: we cannot enable CircleCI for external PRs
This PR rolls back some changing we had to do in the `./circleci` configurations so we can support the new CircleCI OAUTH account we'll create soon.
> Restore `./circleci` configurations for our new CircleCI OAUTH organization

- services/server/README.md
Hey, just fixed a dead link in `server/README.md`.
The link to `lib-sourcify` was still pointing to the old `main` branch, but the actual repo uses `master`. Just a small doc fix to avoid confusion.
> chore: fixed dead link server/README.md

- services/database/migrations/20250828092603_add_signature_tables.sql
- services/database/sourcify-database.sql
Related to #2316 
Should be more efficient than the previous approach. Will again reapply the migration on staging after merging.
> Use signature_type_enum for signature_type in db migrations

- services/server/src/server/services/utils/Database.ts
- services/server/src/server/signature-api/openchain.handlers.ts
- replace the `/stats` endpoint’s three per-type COUNT queries with one grouped query (`SELECT signature_type, COUNT(DISTINCT signature_hash_32)… GROUP BY signature_type`)
- drop the join to `signatures` and read directly from `compiled_contracts_signatures`, so we scan the table once and let Postgres return one row per signature type
- update `getSignaturesStats` to consume the grouped results while preserving zero defaults for any missing type
> Optimize signature stats query

- .circleci/continue_config.yml
- .circleci/new_branch.yml
- .circleci/nightly.yml
- .circleci/test-chains-regularly.yml
- services/database/README.md
- services/database/docker-compose.yml
- services/database/migrations/20250922140427_optimize_signature_search.sql
- services/database/migrations/20250922141802_signature_stats_materialized_view.sql
- services/database/sourcify-database.sql
- services/server/docker-compose.local.yml
- services/server/docker-compose.yml
- services/server/src/server/services/utils/Database.ts
- services/server/src/server/signature-api/openchain.handlers.ts
- services/server/src/signature-database.yaml
- services/server/test/docker-compose.yml
- services/server/test/integration/signature-api/openchain.spec.ts
- Adds GIN index to `signatures.signature` for fast `LIKE` search
- Enables `pg_trgm` for efficient trigram search
- Handles `_` escape
- Adds and underscore function name test and updates other tests to be independent of the order of inserted functions.
- Creates a materialized view `sourcify_stats` for the `/stats` endpoint to use. Adds when this materialized view was last updated and adds that field to the /stats response.
- Adds `pg_cron` to update the stats daily
TODO:
> Optimize signature search and materialized view for /stats

- services/monitor/monitorChains.json
- services/server/src/sourcify-chains-default.json
- services/server/test/chains/chain-tests.spec.ts
- services/server/test/helpers/etherscanInstanceContracts.json
Since Holesky will be shut down end of September, the L2 testnets that use Holesky as L1 will also stop working. Let's clean up and remove the entries for the Holesky-based Celo networks.
> Remove old Celo testnets

- services/database/README.md
- services/database/migrations/20250922141802_signature_stats_materialized_view.sql
- services/database/sourcify-database.sql
- services/server/src/server/services/utils/Database.ts
- services/server/src/server/signature-api/openchain.handlers.ts
- services/server/test/integration/signature-api/openchain.spec.ts
Turns out the original function we wrote was buggy as you can't really UPDATE a materialized view. That's why the refresh failed last night. We can completely get rid of the function and just schedule a direct refresh of the materialized view, and it will take care of the `refreshed_at` columns itself
TODO:
> Remove buggy the refresh_materialized_view function, raise the pg notice to log level
